/**
 * Scan universes — broad, hand-curated coverage of each market: large caps
 * PLUS a deliberate mid- & small-cap tier (~80 extra India names, ~16 Canada),
 * so the screens can hunt where tomorrow's large caps live — without any paid
 * screener API. Size is judged live from market cap (capTierOf in screens.ts),
 * so the "Mid & small-cap compounders" screen and the size filter always use
 * current values, not stale labels.
 *
 * NOT recommendations — candidates. The same scorecard that judges your
 * holdings judges them, live, from free Yahoo data. Names that fail to fetch
 * are reported and skipped. Edit freely — anything with a Yahoo symbol works,
 * and the Screeners tab also accepts a pasted custom list.
 */

export interface CandidateStock {
  symbol: string; // Yahoo symbol
  name: string;
  sector: string; // display hint only; live sector comes from Yahoo
}

export type UniverseCountry = "India" | "Canada" | "United States";

const c = (symbol: string, name: string, sector: string): CandidateStock => ({ symbol, name, sector });

export const UNIVERSES: Record<UniverseCountry, CandidateStock[]> = {
  India: [
    // — IT & tech services —
    c("TCS.NS", "Tata Consultancy Services", "IT Services"),
    c("INFY.NS", "Infosys", "IT Services"),
    c("HCLTECH.NS", "HCL Technologies", "IT Services"),
    c("WIPRO.NS", "Wipro", "IT Services"),
    c("TECHM.NS", "Tech Mahindra", "IT Services"),
    c("LTIM.NS", "LTIMindtree", "IT Services"),
    c("PERSISTENT.NS", "Persistent Systems", "IT Services"),
    c("COFORGE.NS", "Coforge", "IT Services"),
    c("MPHASIS.NS", "Mphasis", "IT Services"),
    c("LTTS.NS", "L&T Technology Services", "ER&D Services"),
    c("TATAELXSI.NS", "Tata Elxsi", "Design / ER&D"),
    c("KPITTECH.NS", "KPIT Technologies", "Auto Software"),
    c("OFSS.NS", "Oracle Financial Services", "Banking Software"),
    c("NAUKRI.NS", "Info Edge (Naukri)", "Internet"),
    c("POLICYBZR.NS", "PB Fintech (Policybazaar)", "Internet / Fintech"),
    c("IRCTC.NS", "IRCTC", "Internet / Travel"),
    // — banks & NBFCs —
    c("HDFCBANK.NS", "HDFC Bank", "Banks"),
    c("ICICIBANK.NS", "ICICI Bank", "Banks"),
    c("KOTAKBANK.NS", "Kotak Mahindra Bank", "Banks"),
    c("AXISBANK.NS", "Axis Bank", "Banks"),
    c("SBIN.NS", "State Bank of India", "Banks"),
    c("INDUSINDBK.NS", "IndusInd Bank", "Banks"),
    c("FEDERALBNK.NS", "Federal Bank", "Banks"),
    c("IDFCFIRSTB.NS", "IDFC FIRST Bank", "Banks"),
    c("BAJFINANCE.NS", "Bajaj Finance", "NBFC"),
    c("BAJAJFINSV.NS", "Bajaj Finserv", "Financial Services"),
    c("CHOLAFIN.NS", "Cholamandalam Finance", "NBFC"),
    c("SHRIRAMFIN.NS", "Shriram Finance", "NBFC"),
    c("MUTHOOTFIN.NS", "Muthoot Finance", "Gold NBFC"),
    c("PFC.NS", "Power Finance Corp", "Infra Finance"),
    c("RECLTD.NS", "REC Ltd", "Infra Finance"),
    // — insurance & capital markets —
    c("HDFCLIFE.NS", "HDFC Life Insurance", "Insurance"),
    c("SBILIFE.NS", "SBI Life Insurance", "Insurance"),
    c("ICICIPRULI.NS", "ICICI Prudential Life", "Insurance"),
    c("ICICIGI.NS", "ICICI Lombard", "General Insurance"),
    c("LICI.NS", "Life Insurance Corp", "Insurance"),
    c("HDFCAMC.NS", "HDFC AMC", "Asset Management"),
    c("CAMS.NS", "CAMS", "Capital-market Infra"),
    c("CDSL.NS", "CDSL", "Depository"),
    c("BSE.NS", "BSE Ltd", "Exchange"),
    c("MCX.NS", "MCX", "Exchange"),
    c("IEX.NS", "Indian Energy Exchange", "Exchange"),
    c("ANGELONE.NS", "Angel One", "Broking"),
    // — consumer staples —
    c("HINDUNILVR.NS", "Hindustan Unilever", "FMCG"),
    c("NESTLEIND.NS", "Nestlé India", "FMCG"),
    c("ITC.NS", "ITC", "FMCG / Tobacco"),
    c("BRITANNIA.NS", "Britannia", "FMCG"),
    c("DABUR.NS", "Dabur", "FMCG"),
    c("MARICO.NS", "Marico", "FMCG"),
    c("GODREJCP.NS", "Godrej Consumer", "FMCG"),
    c("COLPAL.NS", "Colgate-Palmolive India", "FMCG"),
    c("TATACONSUM.NS", "Tata Consumer Products", "FMCG"),
    c("VBL.NS", "Varun Beverages", "Beverages"),
    c("UBL.NS", "United Breweries", "Beverages"),
    c("UNITDSPR.NS", "United Spirits", "Beverages"),
    c("PGHH.NS", "P&G Hygiene & Health", "FMCG"),
    c("JUBLFOOD.NS", "Jubilant FoodWorks", "QSR"),
    // — retail & consumer discretionary —
    c("DMART.NS", "Avenue Supermarts (DMart)", "Retail"),
    c("TRENT.NS", "Trent (Westside/Zudio)", "Retail"),
    c("TITAN.NS", "Titan Company", "Jewellery / Retail"),
    c("PAGEIND.NS", "Page Industries (Jockey)", "Apparel"),
    c("BATAINDIA.NS", "Bata India", "Footwear"),
    c("DIXON.NS", "Dixon Technologies", "Electronics Mfg"),
    c("VOLTAS.NS", "Voltas", "Durables"),
    c("BLUESTARCO.NS", "Blue Star", "Durables"),
    c("CROMPTON.NS", "Crompton Greaves CE", "Durables"),
    c("HAVELLS.NS", "Havells India", "Electricals"),
    c("POLYCAB.NS", "Polycab India", "Cables"),
    c("KEI.NS", "KEI Industries", "Cables"),
    c("INDHOTEL.NS", "Indian Hotels (Taj)", "Hotels"),
    c("INDIGO.NS", "InterGlobe Aviation (IndiGo)", "Airlines"),
    // — autos & ancillaries —
    c("MARUTI.NS", "Maruti Suzuki", "Autos"),
    c("M&M.NS", "Mahindra & Mahindra", "Autos"),
    c("TATAMOTORS.NS", "Tata Motors", "Autos"),
    c("BAJAJ-AUTO.NS", "Bajaj Auto", "2-Wheelers"),
    c("EICHERMOT.NS", "Eicher Motors (Royal Enfield)", "2-Wheelers"),
    c("TVSMOTOR.NS", "TVS Motor", "2-Wheelers"),
    c("HEROMOTOCO.NS", "Hero MotoCorp", "2-Wheelers"),
    c("ASHOKLEY.NS", "Ashok Leyland", "Commercial Vehicles"),
    c("MOTHERSON.NS", "Samvardhana Motherson", "Auto Parts"),
    c("BHARATFORG.NS", "Bharat Forge", "Auto Parts / Forging"),
    c("BALKRISIND.NS", "Balkrishna Industries", "Tyres"),
    c("MRF.NS", "MRF", "Tyres"),
    c("APOLLOTYRE.NS", "Apollo Tyres", "Tyres"),
    c("TIINDIA.NS", "Tube Investments", "Auto / Engineering"),
    c("BOSCHLTD.NS", "Bosch India", "Auto Parts"),
    // — pharma & healthcare —
    c("SUNPHARMA.NS", "Sun Pharma", "Pharma"),
    c("DRREDDY.NS", "Dr. Reddy's", "Pharma"),
    c("CIPLA.NS", "Cipla", "Pharma"),
    c("DIVISLAB.NS", "Divi's Laboratories", "Pharma API"),
    c("TORNTPHARM.NS", "Torrent Pharma", "Pharma"),
    c("LUPIN.NS", "Lupin", "Pharma"),
    c("AUROPHARMA.NS", "Aurobindo Pharma", "Pharma"),
    c("ALKEM.NS", "Alkem Laboratories", "Pharma"),
    c("ZYDUSLIFE.NS", "Zydus Lifesciences", "Pharma"),
    c("IPCALAB.NS", "Ipca Laboratories", "Pharma"),
    c("ABBOTINDIA.NS", "Abbott India", "Pharma MNC"),
    c("BIOCON.NS", "Biocon", "Biotech"),
    c("SYNGENE.NS", "Syngene International", "CRO"),
    c("LAURUSLABS.NS", "Laurus Labs", "Pharma API"),
    c("APOLLOHOSP.NS", "Apollo Hospitals", "Hospitals"),
    c("MAXHEALTH.NS", "Max Healthcare", "Hospitals"),
    c("FORTIS.NS", "Fortis Healthcare", "Hospitals"),
    c("LALPATHLAB.NS", "Dr Lal PathLabs", "Diagnostics"),
    // — energy, utilities, commodities —
    c("RELIANCE.NS", "Reliance Industries", "Conglomerate / Energy"),
    c("ONGC.NS", "ONGC", "Oil & Gas"),
    c("IOC.NS", "Indian Oil", "Refining"),
    c("BPCL.NS", "BPCL", "Refining"),
    c("GAIL.NS", "GAIL", "Gas Utility"),
    c("NTPC.NS", "NTPC", "Power"),
    c("POWERGRID.NS", "Power Grid", "Transmission"),
    c("TATAPOWER.NS", "Tata Power", "Power"),
    c("COALINDIA.NS", "Coal India", "Mining"),
    c("JSWSTEEL.NS", "JSW Steel", "Steel"),
    c("TATASTEEL.NS", "Tata Steel", "Steel"),
    c("HINDALCO.NS", "Hindalco", "Aluminium"),
    c("VEDL.NS", "Vedanta", "Diversified Mining"),
    // — industrials, infra, defence —
    c("LT.NS", "Larsen & Toubro", "E&C"),
    c("SIEMENS.NS", "Siemens India", "Capital Goods"),
    c("ABB.NS", "ABB India", "Capital Goods"),
    c("CGPOWER.NS", "CG Power", "Capital Goods"),
    c("THERMAX.NS", "Thermax", "Capital Goods"),
    c("CUMMINSIND.NS", "Cummins India", "Engines"),
    c("HAL.NS", "Hindustan Aeronautics", "Defence"),
    c("BEL.NS", "Bharat Electronics", "Defence"),
    c("ADANIENT.NS", "Adani Enterprises", "Conglomerate"),
    c("ADANIPORTS.NS", "Adani Ports", "Ports"),
    c("BHARTIARTL.NS", "Bharti Airtel", "Telecom"),
    c("TATACOMM.NS", "Tata Communications", "Telecom Infra"),
    // — cement, chemicals, materials —
    c("ULTRACEMCO.NS", "UltraTech Cement", "Cement"),
    c("SHREECEM.NS", "Shree Cement", "Cement"),
    c("AMBUJACEM.NS", "Ambuja Cements", "Cement"),
    c("JKCEMENT.NS", "JK Cement", "Cement"),
    c("DALBHARAT.NS", "Dalmia Bharat", "Cement"),
    c("GRASIM.NS", "Grasim Industries", "Cement / Chemicals"),
    c("ASIANPAINT.NS", "Asian Paints", "Paints"),
    c("BERGEPAINT.NS", "Berger Paints", "Paints"),
    c("PIDILITIND.NS", "Pidilite Industries", "Adhesives"),
    c("SRF.NS", "SRF", "Specialty Chemicals"),
    c("PIIND.NS", "PI Industries", "Agro Chemicals"),
    c("DEEPAKNTR.NS", "Deepak Nitrite", "Chemicals"),
    c("ASTRAL.NS", "Astral", "Pipes"),
    c("SUPREMEIND.NS", "Supreme Industries", "Plastics"),
    // — real estate —
    c("DLF.NS", "DLF", "Real Estate"),
    c("GODREJPROP.NS", "Godrej Properties", "Real Estate"),
    c("OBEROIRLTY.NS", "Oberoi Realty", "Real Estate"),
    // — mid & small caps: engineering / industrials —
    c("APLAPOLLO.NS", "APL Apollo Tubes", "Steel Tubes"),
    c("SUNDRMFAST.NS", "Sundram Fasteners", "Auto Components"),
    c("SCHAEFFLER.NS", "Schaeffler India", "Bearings"),
    c("TIMKEN.NS", "Timken India", "Bearings"),
    c("SKFINDIA.NS", "SKF India", "Bearings"),
    c("GRINDWELL.NS", "Grindwell Norton", "Abrasives"),
    c("CARBORUNIV.NS", "Carborundum Universal", "Abrasives"),
    c("AIAENG.NS", "AIA Engineering", "Grinding Media"),
    c("RATNAMANI.NS", "Ratnamani Metals & Tubes", "Steel Tubes"),
    c("HONAUT.NS", "Honeywell Automation India", "Industrial Automation"),
    c("3MINDIA.NS", "3M India", "Diversified Industrial"),
    c("KSB.NS", "KSB Ltd", "Pumps"),
    c("INGERRAND.NS", "Ingersoll-Rand India", "Compressors"),
    c("GMMPFAUDLR.NS", "GMM Pfaudler", "Process Equipment"),
    c("ESABINDIA.NS", "ESAB India", "Welding"),
    c("TEGA.NS", "Tega Industries", "Mining Consumables"),
    c("GARFIBRES.NS", "Garware Technical Fibres", "Technical Textiles"),
    c("KAYNES.NS", "Kaynes Technology", "Electronics Manufacturing"),
    c("SYRMA.NS", "Syrma SGS Technology", "Electronics Manufacturing"),
    c("ENDURANCE.NS", "Endurance Technologies", "Auto Components"),
    c("SUPRAJIT.NS", "Suprajit Engineering", "Auto Components"),
    c("EXIDEIND.NS", "Exide Industries", "Batteries"),
    // — mid & small caps: chemicals —
    c("NAVINFLUOR.NS", "Navin Fluorine", "Specialty Chemicals"),
    c("AARTIIND.NS", "Aarti Industries", "Specialty Chemicals"),
    c("ATUL.NS", "Atul Ltd", "Specialty Chemicals"),
    c("VINATIORGA.NS", "Vinati Organics", "Specialty Chemicals"),
    c("FINEORG.NS", "Fine Organic Industries", "Oleochemicals"),
    c("ALKYLAMINE.NS", "Alkyl Amines", "Specialty Chemicals"),
    c("CLEAN.NS", "Clean Science & Technology", "Green Chemistry"),
    c("NOCIL.NS", "NOCIL", "Rubber Chemicals"),
    c("COROMANDEL.NS", "Coromandel International", "Agri Inputs"),
    // — mid & small caps: financials —
    c("AUBANK.NS", "AU Small Finance Bank", "Banks"),
    c("KARURVYSYA.NS", "Karur Vysya Bank", "Banks"),
    c("CUB.NS", "City Union Bank", "Banks"),
    c("CSBBANK.NS", "CSB Bank", "Banks"),
    c("UJJIVANSFB.NS", "Ujjivan Small Finance Bank", "Banks"),
    c("CREDITACC.NS", "CreditAccess Grameen", "Microfinance"),
    c("FIVESTAR.NS", "Five-Star Business Finance", "NBFC"),
    c("APTUS.NS", "Aptus Value Housing", "Housing Finance"),
    c("HOMEFIRST.NS", "Home First Finance", "Housing Finance"),
    c("POONAWALLA.NS", "Poonawalla Fincorp", "NBFC"),
    c("SUNDARMFIN.NS", "Sundaram Finance", "NBFC"),
    c("MFSL.NS", "Max Financial Services", "Insurance"),
    // — mid & small caps: healthcare —
    c("METROPOLIS.NS", "Metropolis Healthcare", "Diagnostics"),
    c("AJANTPHARM.NS", "Ajanta Pharma", "Pharma"),
    c("JBCHEPHARM.NS", "JB Chemicals & Pharma", "Pharma"),
    c("ERIS.NS", "Eris Lifesciences", "Pharma"),
    c("NATCOPHARM.NS", "Natco Pharma", "Pharma"),
    c("POLYMED.NS", "Poly Medicure", "Medical Devices"),
    // — mid & small caps: IT & digital —
    c("CYIENT.NS", "Cyient", "ER&D Services"),
    c("SONATSOFTW.NS", "Sonata Software", "IT Services"),
    c("INTELLECT.NS", "Intellect Design Arena", "Banking Software"),
    c("NEWGEN.NS", "Newgen Software", "Enterprise Software"),
    c("LATENTVIEW.NS", "Latent View Analytics", "Analytics"),
    c("MAPMYINDIA.NS", "C.E. Info Systems (MapmyIndia)", "Digital Maps"),
    c("ROUTE.NS", "Route Mobile", "CPaaS"),
    // — mid & small caps: consumer —
    c("RADICO.NS", "Radico Khaitan", "Spirits"),
    c("EMAMILTD.NS", "Emami", "FMCG"),
    c("JYOTHYLAB.NS", "Jyothy Labs", "FMCG"),
    c("BIKAJI.NS", "Bikaji Foods", "Packaged Foods"),
    c("DEVYANI.NS", "Devyani International", "QSR"),
    c("WESTLIFE.NS", "Westlife Foodworld", "QSR"),
    c("CERA.NS", "Cera Sanitaryware", "Building Products"),
    c("KAJARIACER.NS", "Kajaria Ceramics", "Tiles"),
    c("VGUARD.NS", "V-Guard Industries", "Consumer Electricals"),
    c("TTKPRESTIG.NS", "TTK Prestige", "Kitchen Appliances"),
    c("ORIENTELEC.NS", "Orient Electric", "Consumer Electricals"),
    c("TARSONS.NS", "Tarsons Products", "Labware"),
    c("ROSSARI.NS", "Rossari Biotech", "Specialty Chemicals"),
    c("PRINCEPIP.NS", "Prince Pipes", "Plastics"),
    c("EPL.NS", "EPL Ltd", "Packaging"),
    c("GILLETTE.NS", "Gillette India", "FMCG"),
    c("AKZOINDIA.NS", "Akzo Nobel India", "Paints"),
    // — index constituents: Nifty 100 / Midcap 150 / Smallcap 250 (auto-merged from official index constituents, Aug 2026) —
    c("ADANIENSOL.NS", "ADANIENSOL", "Nifty Next 50"),
    c("ADANIGREEN.NS", "ADANIGREEN", "Nifty Next 50"),
    c("ADANIPOWER.NS", "ADANIPOWER", "Nifty Next 50"),
    c("BAJAJHLDNG.NS", "BAJAJHLDNG", "Nifty Next 50"),
    c("BAJAJHFL.NS", "BAJAJHFL", "Nifty Next 50"),
    c("BANKBARODA.NS", "BANKBARODA", "Nifty Next 50"),
    c("CANBK.NS", "CANBK", "Nifty Next 50"),
    c("HINDZINC.NS", "HINDZINC", "Nifty Next 50"),
    c("HYUNDAI.NS", "HYUNDAI", "Nifty Next 50"),
    c("IRFC.NS", "IRFC", "Nifty Next 50"),
    c("JINDALSTEL.NS", "JINDALSTEL", "Nifty Next 50"),
    c("JSWENERGY.NS", "JSWENERGY", "Nifty Next 50"),
    c("LODHA.NS", "LODHA", "Nifty Next 50"),
    c("MAZDOCK.NS", "MAZDOCK", "Nifty Next 50"),
    c("PNB.NS", "PNB", "Nifty Next 50"),
    c("ENRIN.NS", "ENRIN", "Nifty Next 50"),
    c("SOLARINDS.NS", "SOLARINDS", "Nifty Next 50"),
    c("IDEA.NS", "Vodafone Idea", "Nifty Midcap 150"),
    c("POWERINDIA.NS", "ABB Power Products & Systems India", "Nifty Midcap 150"),
    c("BHEL.NS", "Bharat Heavy Electricals", "Nifty Midcap 150"),
    c("GROWW.NS", "BillionBrains Garage Ventures (Groww)", "Nifty Midcap 150"),
    c("INDIANB.NS", "Indian Bank", "Nifty Midcap 150"),
    c("LENSKART.NS", "Lenskart Solutions", "Nifty Midcap 150"),
    c("ABCAPITAL.NS", "Aditya Birla Capital", "Nifty Midcap 150"),
    c("GVT&D.NS", "GE Vernova T&D India", "Nifty Midcap 150"),
    c("GMRAIRPORT.NS", "GMR Airports", "Nifty Midcap 150"),
    c("PAYTM.NS", "One97 Communications (Paytm)", "Nifty Midcap 150"),
    c("LLOYDSME.NS", "Lloyds Metals & Energy", "Nifty Midcap 150"),
    c("INDUSTOWER.NS", "Indus Towers", "Nifty Midcap 150"),
    c("MANKIND.NS", "Mankind Pharma", "Nifty Midcap 150"),
    c("NYKAA.NS", "FSN E-Commerce (Nykaa)", "Nifty Midcap 150"),
    c("BHARTIHEXA.NS", "Bharti Hexacom", "Nifty Midcap 150"),
    c("NAM-INDIA.NS", "Nippon Life India AMC", "Nifty Midcap 150"),
    c("JSWINFRA.NS", "JSW Infrastructure", "Nifty Midcap 150"),
    c("HINDPETRO.NS", "Hindustan Petroleum", "Nifty Midcap 150"),
    c("LTF.NS", "L&T Finance", "Nifty Midcap 150"),
    c("SWIGGY.NS", "Swiggy", "Nifty Midcap 150"),
    c("OIL.NS", "Oil India", "Nifty Midcap 150"),
    c("NTPCGREEN.NS", "NTPC Green Energy", "Nifty Midcap 150"),
    c("NHPC.NS", "NHPC", "Nifty Midcap 150"),
    c("WAAREEENER.NS", "Waaree Energies", "Nifty Midcap 150"),
    c("NMDC.NS", "NMDC", "Nifty Midcap 150"),
    c("SAIL.NS", "Steel Authority of India", "Nifty Midcap 150"),
    c("NATIONALUM.NS", "National Aluminium", "Nifty Midcap 150"),
    c("UNOMINDA.NS", "Uno Minda", "Nifty Midcap 150"),
    c("YESBANK.NS", "Yes Bank", "Nifty Midcap 150"),
    c("ATGL.NS", "Adani Total Gas", "Nifty Midcap 150"),
    c("PRESTIGE.NS", "Prestige Estates", "Nifty Midcap 150"),
    c("APARINDS.NS", "Apar Industries", "Nifty Midcap 150"),
    c("PHOENIXLTD.NS", "Phoenix Mills", "Nifty Midcap 150"),
    c("GLENMARK.NS", "Glenmark Pharmaceuticals", "Nifty Midcap 150"),
    c("SUZLON.NS", "Suzlon Energy", "Nifty Midcap 150"),
    c("BANKINDIA.NS", "Bank of India", "Nifty Midcap 150"),
    c("TORNTPOWER.NS", "Torrent Power", "Nifty Midcap 150"),
    c("KALYANKJIL.NS", "Kalyan Jewellers", "Nifty Midcap 150"),
    c("GICRE.NS", "General Insurance Corporation", "Nifty Midcap 150"),
    c("MAHABANK.NS", "Bank of Maharashtra", "Nifty Midcap 150"),
    c("SBICARD.NS", "SBI Cards", "Nifty Midcap 150"),
    c("MOTILALOFS.NS", "Motilal Oswal Financial", "Nifty Midcap 150"),
    c("JSL.NS", "Jindal Stainless", "Nifty Midcap 150"),
    c("LINDEINDIA.NS", "Linde India", "Nifty Midcap 150"),
    c("VMM.NS", "Vishal Mega Mart", "Nifty Midcap 150"),
    c("M&MFIN.NS", "M&M Financial Services", "Nifty Midcap 150"),
    c("FLUOROCHEM.NS", "Gujarat Fluorochemicals", "Nifty Midcap 150"),
    c("BDL.NS", "Bharat Dynamics", "Nifty Midcap 150"),
    c("ANTHEM.NS", "Anthem Biosciences", "Nifty Midcap 150"),
    c("GLAXO.NS", "GlaxoSmithKline Pharma", "Nifty Midcap 150"),
    c("360ONE.NS", "360 ONE WAM", "Nifty Midcap 150"),
    c("UPL.NS", "UPL", "Nifty Midcap 150"),
    c("AIIL.NS", "Authum Investment", "Nifty Midcap 150"),
    c("PREMIERENE.NS", "Premier Energies", "Nifty Midcap 150"),
    c("RVNL.NS", "Rail Vikas Nigam", "Nifty Midcap 150"),
    c("PETRONET.NS", "Petronet LNG", "Nifty Midcap 150"),
    c("GODREJIND.NS", "Godrej Industries", "Nifty Midcap 150"),
    c("COCHINSHIP.NS", "Cochin Shipyard", "Nifty Midcap 150"),
    c("CONCOR.NS", "Container Corporation", "Nifty Midcap 150"),
    c("KPRMILL.NS", "K.P.R. Mill", "Nifty Midcap 150"),
    c("PATANJALI.NS", "Patanjali Foods", "Nifty Midcap 150"),
    c("MEDANTA.NS", "Global Health (Medanta)", "Nifty Midcap 150"),
    c("NLCINDIA.NS", "NLC India", "Nifty Midcap 150"),
    c("HUDCO.NS", "HUDCO", "Nifty Midcap 150"),
    c("ESCORTS.NS", "Escorts Kubota", "Nifty Midcap 150"),
    c("HEXT.NS", "Hexaware Technologies", "Nifty Midcap 150"),
    c("GODFRYPHLP.NS", "Godfrey Phillips", "Nifty Midcap 150"),
    c("CRISIL.NS", "CRISIL", "Nifty Midcap 150"),
    c("TATAINVEST.NS", "Tata Investment Corporation", "Nifty Midcap 150"),
    c("IREDA.NS", "IREDA", "Nifty Midcap 150"),
    c("NIACL.NS", "New India Assurance", "Nifty Midcap 150"),
    c("LICHSGFIN.NS", "LIC Housing Finance", "Nifty Midcap 150"),
    c("SJVN.NS", "SJVN", "Nifty Midcap 150"),
    c("AWL.NS", "AWL Agri Business (Adani Wilmar)", "Nifty Midcap 150"),
    c("ACC.NS", "ACC", "Nifty Midcap 150"),
    c("MEESHO.NS", "Meesho", "Nifty Smallcap 250"),
    c("IDBI.NS", "IDBI Bank", "Nifty Smallcap 250"),
    c("ASTERDM.NS", "Aster DM Healthcare", "Nifty Smallcap 250"),
    c("IOB.NS", "Indian Overseas Bank", "Nifty Smallcap 250"),
    c("WELCORP.NS", "Welspun Corp", "Nifty Smallcap 250"),
    c("RBLBANK.NS", "RBL Bank", "Nifty Smallcap 250"),
    c("HINDCOPPER.NS", "Hindustan Copper", "Nifty Smallcap 250"),
    c("FACT.NS", "FACT", "Nifty Smallcap 250"),
    c("SONACOMS.NS", "Sona BLW Precision", "Nifty Smallcap 250"),
    c("PEL.NS", "Piramal Finance", "Nifty Smallcap 250"),
    c("AEGISLOG.NS", "Aegis Logistics", "Nifty Smallcap 250"),
    c("GLAND.NS", "Gland Pharma", "Nifty Smallcap 250"),
    c("ADITYAINFO.NS", "Aditya Infotech", "Nifty Smallcap 250"),
    c("NH.NS", "Narayana Hrudayalaya", "Nifty Smallcap 250"),
    c("HFCL.NS", "HFCL", "Nifty Smallcap 250"),
    c("ANANDRATHI.NS", "Anand Rathi Wealth", "Nifty Smallcap 250"),
    c("PHYSICSWLH.NS", "PhysicsWallah", "Nifty Smallcap 250"),
    c("EMCURE.NS", "Emcure Pharmaceuticals", "Nifty Smallcap 250"),
    c("MANAPPURAM.NS", "Manappuram Finance", "Nifty Smallcap 250"),
    c("STARHEALTH.NS", "Star Health Insurance", "Nifty Smallcap 250"),
    c("HSCL.NS", "Himadri Speciality Chemical", "Nifty Smallcap 250"),
    c("DELHIVERY.NS", "Delhivery", "Nifty Smallcap 250"),
    c("PTCIL.NS", "PTC Industries", "Nifty Smallcap 250"),
    c("UCOBANK.NS", "UCO Bank", "Nifty Smallcap 250"),
    c("NETWEB.NS", "Netweb Technologies", "Nifty Smallcap 250"),
    c("RRKABEL.NS", "R R Kabel", "Nifty Smallcap 250"),
    c("TATATECH.NS", "Tata Technologies", "Nifty Smallcap 250"),
    c("KIMS.NS", "Krishna Institute of Medical Sciences", "Nifty Smallcap 250"),
    c("NUVAMA.NS", "Nuvama Wealth", "Nifty Smallcap 250"),
    c("WOCKPHARMA.NS", "Wockhardt", "Nifty Smallcap 250"),
    c("IKS.NS", "Inventurus Knowledge", "Nifty Smallcap 250"),
    c("SAILIFE.NS", "Sai Life Sciences", "Nifty Smallcap 250"),
    c("MRPL.NS", "Mangalore Refinery", "Nifty Smallcap 250"),
    c("PNBHOUSING.NS", "PNB Housing Finance", "Nifty Smallcap 250"),
    c("ZFCVINDIA.NS", "ZF Commercial Vehicle", "Nifty Smallcap 250"),
    c("KIRLOSENG.NS", "Kirloskar Oil Engines", "Nifty Smallcap 250"),
    c("AEGISVOPAK.NS", "Aegis Vopak Terminals", "Nifty Smallcap 250"),
    c("GRSE.NS", "Garden Reach Shipbuilders", "Nifty Smallcap 250"),
    c("IIFL.NS", "IIFL Finance", "Nifty Smallcap 250"),
    c("NEULANDLAB.NS", "Neuland Laboratories", "Nifty Smallcap 250"),
    c("CHOLAHLDNG.NS", "Cholamandalam Financial Holdings", "Nifty Smallcap 250"),
    c("ACMESOLAR.NS", "ACME Solar", "Nifty Smallcap 250"),
    c("ABSLAMC.NS", "Aditya Birla Sun Life AMC", "Nifty Smallcap 250"),
    c("REDINGTON.NS", "Redington", "Nifty Smallcap 250"),
    c("CENTRALBK.NS", "Central Bank of India", "Nifty Smallcap 250"),
    c("PPLPHARMA.NS", "Piramal Pharma", "Nifty Smallcap 250"),
    c("BANDHANBNK.NS", "Bandhan Bank", "Nifty Smallcap 250"),
    c("SHYAMMETL.NS", "Shyam Metalics", "Nifty Smallcap 250"),
    c("CRAFTSMAN.NS", "Craftsman Automation", "Nifty Smallcap 250"),
    c("SCHNEIDER.NS", "Schneider Electric Infrastructure", "Nifty Smallcap 250"),
    c("ITI.NS", "ITI", "Nifty Smallcap 250"),
    c("DATAPATTNS.NS", "Data Patterns", "Nifty Smallcap 250"),
    c("SUMICHEM.NS", "Sumitomo Chemical India", "Nifty Smallcap 250"),
    c("AMBER.NS", "Amber Enterprises", "Nifty Smallcap 250"),
    c("ACUTAAS.NS", "Acutaas Chemicals", "Nifty Smallcap 250"),
    c("URBANCO.NS", "Urban Company", "Nifty Smallcap 250"),
    c("MSUMI.NS", "Motherson Sumi Wiring", "Nifty Smallcap 250"),
    c("AFFLE.NS", "Affle India", "Nifty Smallcap 250"),
    c("ASAHIINDIA.NS", "Asahi India Glass", "Nifty Smallcap 250"),
    c("GODIGIT.NS", "Go Digit Insurance", "Nifty Smallcap 250"),
    c("GABRIEL.NS", "Gabriel India", "Nifty Smallcap 250"),
    c("PFOCUS.NS", "Prime Focus", "Nifty Smallcap 250"),
    c("NBCC.NS", "NBCC", "Nifty Smallcap 250"),
    c("KPIL.NS", "Kalpataru Projects", "Nifty Smallcap 250"),
    c("FORCEMOT.NS", "Force Motors", "Nifty Smallcap 250"),
    c("IRB.NS", "IRB Infrastructure", "Nifty Smallcap 250"),
    c("EMMVEE.NS", "Emmvee Photovoltaic", "Nifty Smallcap 250"),
    c("CGCL.NS", "Capri Global", "Nifty Smallcap 250"),
    c("TENNECO.NS", "Tenneco Clean Air", "Nifty Smallcap 250"),
    c("PFIZER.NS", "Pfizer", "Nifty Smallcap 250"),
    c("JYOTICNC.NS", "Jyoti CNC Automation", "Nifty Smallcap 250"),
    c("IFCI.NS", "IFCI", "Nifty Smallcap 250"),
    c("BELRISE.NS", "Belrise Industries", "Nifty Smallcap 250"),
    c("ANANTRAJ.NS", "Anant Raj", "Nifty Smallcap 250"),
    c("RAMCOCEM.NS", "Ramco Cements", "Nifty Smallcap 250"),
    c("BRIGADE.NS", "Brigade Enterprises", "Nifty Smallcap 250"),
    c("GRANULES.NS", "Granules India", "Nifty Smallcap 250"),
    c("CHENNPETRO.NS", "Chennai Petroleum", "Nifty Smallcap 250"),
    c("IGL.NS", "Indraprastha Gas", "Nifty Smallcap 250"),
    c("CESC.NS", "CESC", "Nifty Smallcap 250"),
    c("AADHARHFC.NS", "Aadhar Housing Finance", "Nifty Smallcap 250"),
    c("SAGILITY.NS", "Sagility India", "Nifty Smallcap 250"),
    c("FINCABLES.NS", "Finolex Cables", "Nifty Smallcap 250"),
    c("ELGIEQUIP.NS", "Elgi Equipments", "Nifty Smallcap 250"),
    c("FSL.NS", "Firstsource Solutions", "Nifty Smallcap 250"),
    c("HBLENGINE.NS", "HBL Engineering", "Nifty Smallcap 250"),
    c("CHALET.NS", "Chalet Hotels", "Nifty Smallcap 250"),
    c("CAPLIPOINT.NS", "Caplin Point Laboratories", "Nifty Smallcap 250"),
    c("GESHIP.NS", "Great Eastern Shipping", "Nifty Smallcap 250"),
    c("EIH.NS", "EIH", "Nifty Smallcap 250"),
    c("DEEPAKFERT.NS", "Deepak Fertilisers", "Nifty Smallcap 250"),
    c("CASTROLIND.NS", "Castrol India", "Nifty Smallcap 250"),
    c("SUNTV.NS", "Sun TV Network", "Nifty Smallcap 250"),
    c("TBOTEK.NS", "TBO Tek", "Nifty Smallcap 250"),
    c("JINDALSAW.NS", "Jindal Saw", "Nifty Smallcap 250"),
    c("TRITURBINE.NS", "Triveni Turbine", "Nifty Smallcap 250"),
    c("LEELA.NS", "Leela Palaces (Schloss)", "Nifty Smallcap 250"),
    c("BAYERCROP.NS", "Bayer CropScience", "Nifty Smallcap 250"),
    c("PINELABS.NS", "Pine Labs", "Nifty Smallcap 250"),
    c("GMDCLTD.NS", "Gujarat Mineral Development", "Nifty Smallcap 250"),
    c("WELSPUNLIV.NS", "Welspun Living", "Nifty Smallcap 250"),
    c("SARDAEN.NS", "Sarda Energy", "Nifty Smallcap 250"),
    c("CHOICEIN.NS", "Choice International", "Nifty Smallcap 250"),
    c("ONESOURCE.NS", "OneSource Specialty Pharma", "Nifty Smallcap 250"),
    c("SAMMAANCAP.NS", "Sammaan Capital", "Nifty Smallcap 250"),
    c("VTL.NS", "Vardhman Textiles", "Nifty Smallcap 250"),
    c("OLAELEC.NS", "Ola Electric", "Nifty Smallcap 250"),
    c("JSWCEMENT.NS", "JSW Cement", "Nifty Smallcap 250"),
    c("CHAMBLFERT.NS", "Chambal Fertilisers", "Nifty Smallcap 250"),
    c("MINDACORP.NS", "Minda Corporation", "Nifty Smallcap 250"),
    c("TFS.NS", "Travel Food Services", "Nifty Smallcap 250"),
    c("ZENTEC.NS", "Zen Technologies", "Nifty Smallcap 250"),
    c("COHANCE.NS", "Cohance Lifesciences", "Nifty Smallcap 250"),
    c("ECLERX.NS", "eClerx Services", "Nifty Smallcap 250"),
    c("PGEL.NS", "PG Electroplast", "Nifty Smallcap 250"),
    c("ABDL.NS", "Allied Blenders", "Nifty Smallcap 250"),
    c("ARE&M.NS", "Amara Raja Energy", "Nifty Smallcap 250"),
    c("DCMSHRIRAM.NS", "DCM Shriram", "Nifty Smallcap 250"),
    c("KFINTECH.NS", "KFin Technologies", "Nifty Smallcap 250"),
    c("GPIL.NS", "Godawari Power", "Nifty Smallcap 250"),
    c("ZYDUSWELL.NS", "Zydus Wellness", "Nifty Smallcap 250"),
    c("CONCORDBIO.NS", "Concord Biotech", "Nifty Smallcap 250"),
    c("J&KBANK.NS", "Jammu & Kashmir Bank", "Nifty Smallcap 250"),
    c("NAVA.NS", "Nava", "Nifty Smallcap 250"),
    c("HONASA.NS", "Honasa Consumer (Mamaearth)", "Nifty Smallcap 250"),
    c("TATACHEM.NS", "Tata Chemicals", "Nifty Smallcap 250"),
    c("BEML.NS", "BEML", "Nifty Smallcap 250"),
    c("LTFOODS.NS", "LT Foods", "Nifty Smallcap 250"),
    c("JBMA.NS", "JBM Auto", "Nifty Smallcap 250"),
    c("PARADEEP.NS", "Paradeep Phosphates", "Nifty Smallcap 250"),
    c("NIVABUPA.NS", "Niva Bupa Health", "Nifty Smallcap 250"),
    c("VIJAYA.NS", "Vijaya Diagnostic", "Nifty Smallcap 250"),
    c("CARTRADE.NS", "CarTrade Tech", "Nifty Smallcap 250"),
    c("CIEINDIA.NS", "CIE Automotive India", "Nifty Smallcap 250"),
    c("USHAMART.NS", "Usha Martin", "Nifty Smallcap 250"),
    c("RAINBOW.NS", "Rainbow Childrens Medicare", "Nifty Smallcap 250"),
    c("IGIL.NS", "International Gemmological Institute", "Nifty Smallcap 250"),
    c("EIDPARRY.NS", "EID Parry", "Nifty Smallcap 250"),
    c("BALRAMCHIN.NS", "Balrampur Chini Mills", "Nifty Smallcap 250"),
    c("CCL.NS", "CCL Products", "Nifty Smallcap 250"),
    c("CEATLTD.NS", "CEAT", "Nifty Smallcap 250"),
    c("JUBLPHARMA.NS", "Jubilant Pharmova", "Nifty Smallcap 250"),
    c("ENGINERSIN.NS", "Engineers India", "Nifty Smallcap 250"),
    c("ANURAS.NS", "Anupam Rasayan", "Nifty Smallcap 250"),
    c("JSWDULUX.NS", "JSW Paints (Dulux)", "Nifty Smallcap 250"),
    c("GRAPHITE.NS", "Graphite India", "Nifty Smallcap 250"),
    c("GALLANTT.NS", "Gallantt Metal", "Nifty Smallcap 250"),
    c("HEG.NS", "HEG", "Nifty Smallcap 250"),
    c("ACE.NS", "Action Construction Equipment", "Nifty Smallcap 250"),
    c("SOBHA.NS", "Sobha", "Nifty Smallcap 250"),
    c("INDGN.NS", "Indegene", "Nifty Smallcap 250"),
    c("SCI.NS", "Shipping Corporation of India", "Nifty Smallcap 250"),
    c("DOMS.NS", "DOMS Industries", "Nifty Smallcap 250"),
    c("GRAVITA.NS", "Gravita India", "Nifty Smallcap 250"),
    c("RKFORGE.NS", "Ramkrishna Forgings", "Nifty Smallcap 250"),
    c("SPLPETRO.NS", "Supreme Petrochem", "Nifty Smallcap 250"),
    c("INOXWIND.NS", "Inox Wind", "Nifty Smallcap 250"),
    c("PCBL.NS", "PCBL", "Nifty Smallcap 250"),
    c("TRIDENT.NS", "Trident", "Nifty Smallcap 250"),
    c("JMFINANCIL.NS", "JM Financial", "Nifty Smallcap 250"),
    c("PVRINOX.NS", "PVR INOX", "Nifty Smallcap 250"),
    c("BLUEDART.NS", "Blue Dart Express", "Nifty Smallcap 250"),
    c("JPPOWER.NS", "Jaiprakash Power", "Nifty Smallcap 250"),
    c("TECHNOE.NS", "Techno Electric", "Nifty Smallcap 250"),
    c("IRCON.NS", "Ircon International", "Nifty Smallcap 250"),
    c("KEC.NS", "KEC International", "Nifty Smallcap 250"),
    c("NUVOCO.NS", "Nuvoco Vistas", "Nifty Smallcap 250"),
    c("UTIAMC.NS", "UTI AMC", "Nifty Smallcap 250"),
    c("INDIACEM.NS", "India Cements", "Nifty Smallcap 250"),
    c("TITAGARH.NS", "Titagarh Rail Systems", "Nifty Smallcap 250"),
    c("JUBLINGREA.NS", "Jubilant Ingrevia", "Nifty Smallcap 250"),
    c("SIGNATURE.NS", "Signatureglobal", "Nifty Smallcap 250"),
    c("BLUEJET.NS", "Blue Jet Healthcare", "Nifty Smallcap 250"),
    c("MGL.NS", "Mahanagar Gas", "Nifty Smallcap 250"),
    c("JKTYRE.NS", "JK Tyre", "Nifty Smallcap 250"),
    c("ZENSARTECH.NS", "Zensar Technologies", "Nifty Smallcap 250"),
    c("CANFINHOME.NS", "Can Fin Homes", "Nifty Smallcap 250"),
    c("OLECTRA.NS", "Olectra Greentech", "Nifty Smallcap 250"),
    c("AAVAS.NS", "Aavas Financiers", "Nifty Smallcap 250"),
    c("JWL.NS", "Jupiter Wagons", "Nifty Smallcap 250"),
    c("RITES.NS", "RITES", "Nifty Smallcap 250"),
    c("INDIAMART.NS", "IndiaMART", "Nifty Smallcap 250"),
    c("ABLBL.NS", "Aditya Birla Lifestyle", "Nifty Smallcap 250"),
    c("AFCONS.NS", "Afcons Infrastructure", "Nifty Smallcap 250"),
    c("SBFC.NS", "SBFC Finance", "Nifty Smallcap 250"),
    c("JAINREC.NS", "Jain Resource Recycling", "Nifty Smallcap 250"),
    c("FIRSTCRY.NS", "Brainbees (FirstCry)", "Nifty Smallcap 250"),
    c("ZEEL.NS", "Zee Entertainment", "Nifty Smallcap 250"),
    c("BLS.NS", "BLS International", "Nifty Smallcap 250"),
    c("BBTC.NS", "Bombay Burmah", "Nifty Smallcap 250"),
    c("ELECON.NS", "Elecon Engineering", "Nifty Smallcap 250"),
    c("SAREGAMA.NS", "Saregama India", "Nifty Smallcap 250"),
    c("WHIRLPOOL.NS", "Whirlpool of India", "Nifty Smallcap 250"),
    c("MMTC.NS", "MMTC", "Nifty Smallcap 250"),
    c("RPOWER.NS", "Reliance Power", "Nifty Smallcap 250"),
    c("SWANCORP.NS", "Swan Corp", "Nifty Smallcap 250"),
    c("NCC.NS", "NCC", "Nifty Smallcap 250"),
    c("TARIL.NS", "Transformers & Rectifiers", "Nifty Smallcap 250"),
    c("TEJASNET.NS", "Tejas Networks", "Nifty Smallcap 250"),
    c("RAILTEL.NS", "RailTel", "Nifty Smallcap 250"),
    c("LEMONTREE.NS", "Lemon Tree Hotels", "Nifty Smallcap 250"),
    c("BSOFT.NS", "Birlasoft", "Nifty Smallcap 250"),
    c("SAPPHIRE.NS", "Sapphire Foods", "Nifty Smallcap 250"),
    c("RHIM.NS", "RHI Magnesita India", "Nifty Smallcap 250"),
    c("TTML.NS", "Tata Teleservices Maharashtra", "Nifty Smallcap 250"),
    c("ABFRL.NS", "Aditya Birla Fashion", "Nifty Smallcap 250"),
  ],
  Canada: [
    // — software & tech —
    c("CSU.TO", "Constellation Software", "Software"),
    c("TOI.V", "Topicus.com", "Software"),
    c("SHOP.TO", "Shopify", "Software"),
    c("OTEX.TO", "OpenText", "Software"),
    c("DSG.TO", "Descartes Systems", "Software"),
    c("KXS.TO", "Kinaxis", "Software"),
    c("ENGH.TO", "Enghouse Systems", "Software"),
    c("GIB-A.TO", "CGI Inc", "IT Services"),
    c("CLS.TO", "Celestica", "Electronics Mfg"),
    // — consumer —
    c("ATD.TO", "Alimentation Couche-Tard", "Convenience Retail"),
    c("DOL.TO", "Dollarama", "Discount Retail"),
    c("L.TO", "Loblaw Companies", "Grocery"),
    c("MRU.TO", "Metro Inc", "Grocery"),
    c("EMP-A.TO", "Empire (Sobeys)", "Grocery"),
    c("WN.TO", "George Weston", "Consumer Holdings"),
    c("SAP.TO", "Saputo", "Dairy"),
    c("PBH.TO", "Premium Brands", "Food"),
    c("QSR.TO", "Restaurant Brands (Tim Hortons)", "QSR"),
    c("MTY.TO", "MTY Food Group", "QSR Franchisor"),
    c("GIL.TO", "Gildan Activewear", "Apparel"),
    c("ATZ.TO", "Aritzia", "Apparel Retail"),
    c("GOOS.TO", "Canada Goose", "Apparel"),
    c("DOO.TO", "BRP (Ski-Doo)", "Rec Vehicles"),
    c("MG.TO", "Magna International", "Auto Parts"),
    // — rails, transport, industrials —
    c("CNR.TO", "Canadian National Railway", "Rails"),
    c("CP.TO", "Canadian Pacific Kansas City", "Rails"),
    c("TFII.TO", "TFI International", "Trucking"),
    c("WCN.TO", "Waste Connections", "Waste"),
    c("TIH.TO", "Toromont Industries", "Equipment Dealer"),
    c("FTT.TO", "Finning International", "Equipment Dealer"),
    c("RBA.TO", "RB Global (Ritchie Bros)", "Auctions"),
    c("WSP.TO", "WSP Global", "Engineering"),
    c("STN.TO", "Stantec", "Engineering"),
    c("ATRL.TO", "AtkinsRéalis", "Engineering"),
    c("BYD.TO", "Boyd Group", "Collision Repair"),
    c("CAE.TO", "CAE", "Simulation / Training"),
    c("BBD-B.TO", "Bombardier", "Business Jets"),
    c("AC.TO", "Air Canada", "Airlines"),
    c("CIGI.TO", "Colliers International", "Real Estate Services"),
    c("FSV.TO", "FirstService", "Property Services"),
    c("SJ.TO", "Stella-Jones", "Wood Products"),
    c("WFG.TO", "West Fraser Timber", "Lumber"),
    // — banks, insurance, asset mgmt —
    c("RY.TO", "Royal Bank of Canada", "Banks"),
    c("TD.TO", "TD Bank", "Banks"),
    c("BMO.TO", "Bank of Montreal", "Banks"),
    c("BNS.TO", "Bank of Nova Scotia", "Banks"),
    c("CM.TO", "CIBC", "Banks"),
    c("NA.TO", "National Bank of Canada", "Banks"),
    c("EQB.TO", "EQB Inc", "Digital Bank"),
    c("GSY.TO", "goeasy", "Consumer Lending"),
    c("EFN.TO", "Element Fleet", "Fleet Management"),
    c("IFC.TO", "Intact Financial", "P&C Insurance"),
    c("FFH.TO", "Fairfax Financial", "Insurance / Holdings"),
    c("DFY.TO", "Definity Financial", "P&C Insurance"),
    c("SLF.TO", "Sun Life Financial", "Life Insurance"),
    c("MFC.TO", "Manulife", "Life Insurance"),
    c("GWO.TO", "Great-West Lifeco", "Life Insurance"),
    c("IAG.TO", "iA Financial", "Life Insurance"),
    c("POW.TO", "Power Corporation", "Financial Holdings"),
    c("IGM.TO", "IGM Financial", "Asset Management"),
    c("X.TO", "TMX Group", "Exchange"),
    c("BN.TO", "Brookfield Corp", "Alt. Assets"),
    c("BAM.TO", "Brookfield Asset Mgmt", "Alt. Assets"),
    c("ONEX.TO", "Onex", "Private Equity"),
    c("TRI.TO", "Thomson Reuters", "Info Services"),
    // — energy & pipelines —
    c("ENB.TO", "Enbridge", "Pipelines"),
    c("TRP.TO", "TC Energy", "Pipelines"),
    c("PPL.TO", "Pembina Pipeline", "Pipelines"),
    c("KEY.TO", "Keyera", "Midstream"),
    c("ALA.TO", "AltaGas", "Midstream / Utility"),
    c("CNQ.TO", "Canadian Natural Resources", "Oil & Gas"),
    c("SU.TO", "Suncor Energy", "Oil & Gas"),
    c("IMO.TO", "Imperial Oil", "Oil & Gas"),
    c("CVE.TO", "Cenovus Energy", "Oil & Gas"),
    c("TOU.TO", "Tourmaline Oil", "Natural Gas"),
    c("PKI.TO", "Parkland", "Fuel Distribution"),
    // — utilities & telecom —
    c("FTS.TO", "Fortis", "Utilities"),
    c("EMA.TO", "Emera", "Utilities"),
    c("H.TO", "Hydro One", "Utilities"),
    c("CU.TO", "Canadian Utilities", "Utilities"),
    c("CPX.TO", "Capital Power", "Power"),
    c("NPI.TO", "Northland Power", "Renewables"),
    c("T.TO", "Telus", "Telecom"),
    c("BCE.TO", "BCE", "Telecom"),
    c("RCI-B.TO", "Rogers Communications", "Telecom"),
    c("QBR-B.TO", "Quebecor", "Telecom / Media"),
    // — materials & miners —
    c("NTR.TO", "Nutrien", "Fertilizers"),
    c("MX.TO", "Methanex", "Chemicals"),
    c("CCL-B.TO", "CCL Industries", "Packaging"),
    c("AEM.TO", "Agnico Eagle Mines", "Gold"),
    c("ABX.TO", "Barrick Gold", "Gold"),
    c("FNV.TO", "Franco-Nevada", "Royalties"),
    c("WPM.TO", "Wheaton Precious Metals", "Streaming"),
    c("K.TO", "Kinross Gold", "Gold"),
    c("CCO.TO", "Cameco", "Uranium"),
    c("TECK-B.TO", "Teck Resources", "Diversified Mining"),
    c("FM.TO", "First Quantum Minerals", "Copper"),
    c("LUN.TO", "Lundin Mining", "Copper"),
    // — mid & small caps —
    c("TVK.TO", "TerraVest Industries", "Industrial Products"),
    c("BDGI.TO", "Badger Infrastructure", "Excavation Services"),
    c("SIS.TO", "Savaria", "Accessibility Equipment"),
    c("JWEL.TO", "Jamieson Wellness", "Consumer Health"),
    c("WELL.TO", "WELL Health Technologies", "Health Tech"),
    c("PET.TO", "Pet Valu Holdings", "Pet Retail"),
    c("GDI.TO", "GDI Integrated Facility Services", "Facility Services"),
    c("ADEN.TO", "ADENTRA", "Building Products Distribution"),
    c("AND.TO", "Andlauer Healthcare Group", "Healthcare Logistics"),
    c("CGO.TO", "Cogeco Inc", "Telecom / Media"),
    c("HPS-A.TO", "Hammond Power Solutions", "Electrical Equipment"),
    c("TSU.TO", "Trisura Group", "Specialty Insurance"),
    c("DCBO.TO", "Docebo", "Learning Software"),
    c("MDA.TO", "MDA Space", "Space Technology"),
    c("DNTL.TO", "dentalcorp Holdings", "Dental Clinics"),
    c("CTS.TO", "Converge Technology", "IT Solutions"),
    // — index constituents: S&P/TSX Composite (auto-merged from official index constituents, Aug 2026) —
    c("VNP.TO", "VNP", "TSX Composite"),
    c("ABRA.TO", "ABRA", "TSX Composite"),
    c("AAV.TO", "AAV", "TSX Composite"),
    c("ARE.TO", "ARE", "TSX Composite"),
    c("AGI.TO", "AGI", "TSX Composite"),
    c("AQN.TO", "AQN", "TSX Composite"),
    c("AAUC.TO", "AAUC", "TSX Composite"),
    c("AP-UN.TO", "AP", "TSX Composite"),
    c("AIF.TO", "AIF", "TSX Composite"),
    c("USA.TO", "USA", "TSX Composite"),
    c("ARX.TO", "ARX", "TSX Composite"),
    c("ARIS.TO", "ARIS", "TSX Composite"),
    c("ACO-X.TO", "ACO", "TSX Composite"),
    c("ATH.TO", "ATH", "TSX Composite"),
    c("ATS.TO", "ATS", "TSX Composite"),
    c("ASM.TO", "ASM", "TSX Composite"),
    c("AYA.TO", "AYA", "TSX Composite"),
    c("BTO.TO", "BTO", "TSX Composite"),
    c("BHC.TO", "BHC", "TSX Composite"),
    c("BTE.TO", "BTE", "TSX Composite"),
    c("BIR.TO", "BIR", "TSX Composite"),
    c("BDT.TO", "BDT", "TSX Composite"),
    c("BB.TO", "BB", "TSX Composite"),
    c("BEI-UN.TO", "BEI", "TSX Composite"),
    c("BLX.TO", "BLX", "TSX Composite"),
    c("BBUC.TO", "BBUC", "TSX Composite"),
    c("BIP-UN.TO", "BIP", "TSX Composite"),
    c("BEP-UN.TO", "BEP", "TSX Composite"),
    c("CAR-UN.TO", "CAR", "TSX Composite"),
    c("CTC-A.TO", "CTC.A", "TSX Composite"),
    c("CS.TO", "CS", "TSX Composite"),
    c("CJT.TO", "CJT", "TSX Composite"),
    c("CG.TO", "CG", "TSX Composite"),
    c("CEU.TO", "CEU", "TSX Composite"),
    c("CSH-UN.TO", "CSH", "TSX Composite"),
    c("CHP-UN.TO", "CHP", "TSX Composite"),
    c("CCA.TO", "CCA", "TSX Composite"),
    c("CRR-UN.TO", "CRR", "TSX Composite"),
    c("CRT-UN.TO", "CRT", "TSX Composite"),
    c("CURA.TO", "CURA", "TSX Composite"),
    c("DML.TO", "DML", "TSX Composite"),
    c("DSV.TO", "DSV", "TSX Composite"),
    c("DIR-UN.TO", "DIR", "TSX Composite"),
    c("DPM.TO", "DPM", "TSX Composite"),
    c("ELD.TO", "ELD", "TSX Composite"),
    c("EDR.TO", "EDR", "TSX Composite"),
    c("EFR.TO", "EFR", "TSX Composite"),
    c("EFX.TO", "EFX", "TSX Composite"),
    c("EQX.TO", "EQX", "TSX Composite"),
    c("ERO.TO", "ERO", "TSX Composite"),
    c("EIF.TO", "EIF", "TSX Composite"),
    c("FCR-UN.TO", "FCR", "TSX Composite"),
    c("AG.TO", "AG", "TSX Composite"),
    c("FVI.TO", "FVI", "TSX Composite"),
    c("FRU.TO", "FRU", "TSX Composite"),
    c("GMIN.TO", "GMIN", "TSX Composite"),
    c("GFL.TO", "GFL", "TSX Composite"),
    c("GEI.TO", "GEI", "TSX Composite"),
    c("GRT-UN.TO", "GRT", "TSX Composite"),
    c("HR-UN.TO", "HR", "TSX Composite"),
    c("HWX.TO", "HWX", "TSX Composite"),
    c("HBM.TO", "HBM", "TSX Composite"),
    c("IAU.TO", "IAU", "TSX Composite"),
    c("IMG.TO", "IMG", "TSX Composite"),
    c("IPCO.TO", "IPCO", "TSX Composite"),
    c("IIP-UN.TO", "IIP", "TSX Composite"),
    c("IVN.TO", "IVN", "TSX Composite"),
    c("KNT.TO", "KNT", "TSX Composite"),
    c("KEL.TO", "KEL", "TSX Composite"),
    c("KMP-UN.TO", "KMP", "TSX Composite"),
    c("LIF.TO", "LIF", "TSX Composite"),
    c("LB.TO", "LB", "TSX Composite"),
    c("LSPD.TO", "LSPD", "TSX Composite"),
    c("LNR.TO", "LNR", "TSX Composite"),
    c("LAC.TO", "LAC", "TSX Composite"),
    c("LUG.TO", "LUG", "TSX Composite"),
    c("MFI.TO", "MFI", "TSX Composite"),
    c("MAU.TO", "MAU", "TSX Composite"),
    c("MTL.TO", "MTL", "TSX Composite"),
    c("NXE.TO", "NXE", "TSX Composite"),
    c("NFI.TO", "NFI", "TSX Composite"),
    c("NGEX.TO", "NGEX", "TSX Composite"),
    c("NWC.TO", "NWC", "TSX Composite"),
    c("NG.TO", "NG", "TSX Composite"),
    c("OGC.TO", "OGC", "TSX Composite"),
    c("OLA.TO", "OLA", "TSX Composite"),
    c("OR.TO", "OR", "TSX Composite"),
    c("PAAS.TO", "PAAS", "TSX Composite"),
    c("POU.TO", "POU", "TSX Composite"),
    c("PXT.TO", "PXT", "TSX Composite"),
    c("PPTA.TO", "PPTA", "TSX Composite"),
    c("PEY.TO", "PEY", "TSX Composite"),
    c("PSK.TO", "PSK", "TSX Composite"),
    c("PMZ-UN.TO", "PMZ", "TSX Composite"),
    c("RCH.TO", "RCH", "TSX Composite"),
    c("REI-UN.TO", "REI", "TSX Composite"),
    c("RUS.TO", "RUS", "TSX Composite"),
    c("SEA.TO", "SEA", "TSX Composite"),
    c("SES.TO", "SES", "TSX Composite"),
    c("SIA.TO", "SIA", "TSX Composite"),
    c("SVM.TO", "SVM", "TSX Composite"),
    c("SKE.TO", "SKE", "TSX Composite"),
    c("SRU-UN.TO", "SRU", "TSX Composite"),
    c("SOBO.TO", "SOBO", "TSX Composite"),
    c("SII.TO", "SII", "TSX Composite"),
    c("SSRM.TO", "SSRM", "TSX Composite"),
    c("SCR.TO", "SCR", "TSX Composite"),
    c("SPB.TO", "SPB", "TSX Composite"),
    c("TVE.TO", "TVE", "TSX Composite"),
    c("TKO.TO", "TKO", "TSX Composite"),
    c("TPZ.TO", "TPZ", "TSX Composite"),
    c("TXG.TO", "TXG", "TSX Composite"),
    c("TA.TO", "TA", "TSX Composite"),
    c("TCL-A.TO", "TCL.A", "TSX Composite"),
    c("TFPM.TO", "TFPM", "TSX Composite"),
    c("VET.TO", "VET", "TSX Composite"),
    c("VITL-UN.TO", "VITL", "TSX Composite"),
    c("VZLA.TO", "VZLA", "TSX Composite"),
    c("WDO.TO", "WDO", "TSX Composite"),
    c("WCP.TO", "WCP", "TSX Composite"),
    c("WPK.TO", "WPK", "TSX Composite"),
  ],
  "United States": [
    // — mega tech & semis —
    c("AAPL", "Apple", "Technology"),
    c("MSFT", "Microsoft", "Technology"),
    c("GOOGL", "Alphabet", "Communication"),
    c("AMZN", "Amazon", "Consumer / Cloud"),
    c("META", "Meta Platforms", "Communication"),
    c("NVDA", "NVIDIA", "Semiconductors"),
    c("AVGO", "Broadcom", "Semiconductors"),
    c("AMD", "AMD", "Semiconductors"),
    c("QCOM", "Qualcomm", "Semiconductors"),
    c("TXN", "Texas Instruments", "Semiconductors"),
    c("AMAT", "Applied Materials", "Semi Equipment"),
    c("LRCX", "Lam Research", "Semi Equipment"),
    c("KLAC", "KLA Corp", "Semi Equipment"),
    c("MU", "Micron", "Memory"),
    c("TSLA", "Tesla", "Autos / Energy"),
    // — software & internet —
    c("ADBE", "Adobe", "Software"),
    c("CRM", "Salesforce", "Software"),
    c("ORCL", "Oracle", "Software"),
    c("INTU", "Intuit", "Software"),
    c("NOW", "ServiceNow", "Software"),
    c("SNPS", "Synopsys", "EDA Software"),
    c("CDNS", "Cadence Design", "EDA Software"),
    c("ADSK", "Autodesk", "Software"),
    c("PANW", "Palo Alto Networks", "Cybersecurity"),
    c("CRWD", "CrowdStrike", "Cybersecurity"),
    c("FTNT", "Fortinet", "Cybersecurity"),
    c("ACN", "Accenture", "IT Services"),
    c("NFLX", "Netflix", "Streaming"),
    c("UBER", "Uber", "Platforms"),
    c("ABNB", "Airbnb", "Platforms"),
    c("BKNG", "Booking Holdings", "Travel"),
    // — payments & financials —
    c("V", "Visa", "Payments"),
    c("MA", "Mastercard", "Payments"),
    c("AXP", "American Express", "Payments / Lending"),
    c("PYPL", "PayPal", "Payments"),
    c("JPM", "JPMorgan Chase", "Banks"),
    c("GS", "Goldman Sachs", "Investment Banking"),
    c("MS", "Morgan Stanley", "Investment Banking"),
    c("WFC", "Wells Fargo", "Banks"),
    c("SCHW", "Charles Schwab", "Brokerage"),
    c("BLK", "BlackRock", "Asset Management"),
    c("BX", "Blackstone", "Alt. Assets"),
    c("KKR", "KKR", "Alt. Assets"),
    c("APO", "Apollo Global", "Alt. Assets"),
    c("BRK-B", "Berkshire Hathaway", "Conglomerate"),
    c("SPGI", "S&P Global", "Info Services"),
    c("MCO", "Moody's", "Info Services"),
    c("ICE", "Intercontinental Exchange", "Exchanges"),
    c("CME", "CME Group", "Exchanges"),
    c("NDAQ", "Nasdaq", "Exchanges"),
    c("PGR", "Progressive", "Insurance"),
    c("CB", "Chubb", "Insurance"),
    c("TRV", "Travelers", "Insurance"),
    c("MMC", "Marsh & McLennan", "Insurance Brokerage"),
    c("AON", "Aon", "Insurance Brokerage"),
    c("AJG", "Arthur J. Gallagher", "Insurance Brokerage"),
    // — healthcare —
    c("UNH", "UnitedHealth", "Managed Care"),
    c("ELV", "Elevance Health", "Managed Care"),
    c("HCA", "HCA Healthcare", "Hospitals"),
    c("MCK", "McKesson", "Drug Distribution"),
    c("LLY", "Eli Lilly", "Pharma"),
    c("ABBV", "AbbVie", "Pharma"),
    c("MRK", "Merck", "Pharma"),
    c("JNJ", "Johnson & Johnson", "Healthcare"),
    c("AMGN", "Amgen", "Biotech"),
    c("GILD", "Gilead Sciences", "Biotech"),
    c("VRTX", "Vertex Pharmaceuticals", "Biotech"),
    c("REGN", "Regeneron", "Biotech"),
    c("ZTS", "Zoetis", "Animal Health"),
    c("TMO", "Thermo Fisher", "Life Sciences"),
    c("DHR", "Danaher", "Life Sciences"),
    c("A", "Agilent", "Life Sciences"),
    c("ABT", "Abbott Laboratories", "Med Devices"),
    c("SYK", "Stryker", "Med Devices"),
    c("BSX", "Boston Scientific", "Med Devices"),
    c("ISRG", "Intuitive Surgical", "Med Devices"),
    c("EW", "Edwards Lifesciences", "Med Devices"),
    c("IDXX", "IDEXX Laboratories", "Vet Diagnostics"),
    c("BDX", "Becton Dickinson", "Med Devices"),
    // — consumer —
    c("COST", "Costco", "Retail"),
    c("WMT", "Walmart", "Retail"),
    c("TGT", "Target", "Retail"),
    c("HD", "Home Depot", "Home Improvement"),
    c("LOW", "Lowe's", "Home Improvement"),
    c("TJX", "TJX Companies", "Off-price Retail"),
    c("ROST", "Ross Stores", "Off-price Retail"),
    c("ORLY", "O'Reilly Automotive", "Auto Parts Retail"),
    c("AZO", "AutoZone", "Auto Parts Retail"),
    c("TSCO", "Tractor Supply", "Rural Retail"),
    c("LULU", "Lululemon", "Apparel"),
    c("NKE", "Nike", "Apparel"),
    c("MCD", "McDonald's", "Restaurants"),
    c("SBUX", "Starbucks", "Restaurants"),
    c("CMG", "Chipotle", "Restaurants"),
    c("YUM", "Yum! Brands", "Restaurants"),
    c("PG", "Procter & Gamble", "Staples"),
    c("KO", "Coca-Cola", "Beverages"),
    c("PEP", "PepsiCo", "Beverages"),
    c("MNST", "Monster Beverage", "Beverages"),
    c("PM", "Philip Morris Intl", "Tobacco"),
    c("MDLZ", "Mondelez", "Snacks"),
    c("HSY", "Hershey", "Confectionery"),
    c("GIS", "General Mills", "Packaged Food"),
    c("CL", "Colgate-Palmolive", "Staples"),
    c("KMB", "Kimberly-Clark", "Staples"),
    c("DIS", "Disney", "Media"),
    // — industrials —
    c("GE", "GE Aerospace", "Aerospace"),
    c("RTX", "RTX Corp", "Aerospace & Defence"),
    c("LMT", "Lockheed Martin", "Defence"),
    c("NOC", "Northrop Grumman", "Defence"),
    c("GD", "General Dynamics", "Defence"),
    c("TDG", "TransDigm", "Aerospace Parts"),
    c("HON", "Honeywell", "Industrials"),
    c("ETN", "Eaton", "Electrical"),
    c("EMR", "Emerson Electric", "Automation"),
    c("PH", "Parker Hannifin", "Motion Control"),
    c("ITW", "Illinois Tool Works", "Industrials"),
    c("CMI", "Cummins", "Engines"),
    c("PCAR", "PACCAR", "Trucks"),
    c("CAT", "Caterpillar", "Machinery"),
    c("DE", "Deere & Co", "Machinery"),
    c("UNP", "Union Pacific", "Rails"),
    c("CSX", "CSX", "Rails"),
    c("NSC", "Norfolk Southern", "Rails"),
    c("UPS", "UPS", "Logistics"),
    c("FDX", "FedEx", "Logistics"),
    c("WM", "Waste Management", "Waste"),
    c("RSG", "Republic Services", "Waste"),
    c("CTAS", "Cintas", "Uniform Services"),
    c("FAST", "Fastenal", "Distribution"),
    c("GWW", "W.W. Grainger", "Distribution"),
    c("ROP", "Roper Technologies", "Software / Industrials"),
    c("AME", "AMETEK", "Instruments"),
    c("TT", "Trane Technologies", "HVAC"),
    c("ADP", "ADP", "Payroll"),
    c("PAYX", "Paychex", "Payroll"),
    // — energy, utilities, materials —
    c("XOM", "ExxonMobil", "Oil & Gas"),
    c("CVX", "Chevron", "Oil & Gas"),
    c("COP", "ConocoPhillips", "Oil & Gas"),
    c("NEE", "NextEra Energy", "Utilities"),
    c("SO", "Southern Company", "Utilities"),
    c("DUK", "Duke Energy", "Utilities"),
    c("LIN", "Linde", "Industrial Gases"),
    c("APD", "Air Products", "Industrial Gases"),
    c("SHW", "Sherwin-Williams", "Paints"),
    c("ECL", "Ecolab", "Specialty Chemicals"),
    // — index constituents: S&P 500 + S&P MidCap 400 (auto-merged from official index constituents, Aug 2026) —
    c("MMM", "MMM", "S&P 500"),
    c("AOS", "AOS", "S&P 500"),
    c("AES", "AES", "S&P 500"),
    c("AFL", "AFL", "S&P 500"),
    c("AKAM", "AKAM", "S&P 500"),
    c("ALB", "ALB", "S&P 500"),
    c("ARE", "ARE", "S&P 500"),
    c("ALGN", "ALGN", "S&P 500"),
    c("ALLE", "ALLE", "S&P 500"),
    c("LNT", "LNT", "S&P 500"),
    c("ALL", "ALL", "S&P 500"),
    c("MO", "MO", "S&P 500"),
    c("AMCR", "AMCR", "S&P 500"),
    c("AEE", "AEE", "S&P 500"),
    c("AEP", "AEP", "S&P 500"),
    c("AIG", "AIG", "S&P 500"),
    c("AMT", "AMT", "S&P 500"),
    c("AWK", "AWK", "S&P 500"),
    c("AMP", "AMP", "S&P 500"),
    c("APH", "APH", "S&P 500"),
    c("ADI", "ADI", "S&P 500"),
    c("APA", "APA", "S&P 500"),
    c("APP", "APP", "S&P 500"),
    c("APTV", "APTV", "S&P 500"),
    c("ACGL", "ACGL", "S&P 500"),
    c("ADM", "ADM", "S&P 500"),
    c("ARES", "ARES", "S&P 500"),
    c("ANET", "ANET", "S&P 500"),
    c("AIZ", "AIZ", "S&P 500"),
    c("T", "T", "S&P 500"),
    c("ATO", "ATO", "S&P 500"),
    c("AVB", "AVB", "S&P 500"),
    c("AVY", "AVY", "S&P 500"),
    c("AXON", "AXON", "S&P 500"),
    c("BKR", "BKR", "S&P 500"),
    c("BALL", "BALL", "S&P 500"),
    c("BAC", "BAC", "S&P 500"),
    c("BAX", "BAX", "S&P 500"),
    c("BBY", "BBY", "S&P 500"),
    c("TECH", "TECH", "S&P 500"),
    c("BIIB", "BIIB", "S&P 500"),
    c("XYZ", "XYZ", "S&P 500"),
    c("BNY", "BNY", "S&P 500"),
    c("BA", "BA", "S&P 500"),
    c("BMY", "BMY", "S&P 500"),
    c("BR", "BR", "S&P 500"),
    c("BRO", "BRO", "S&P 500"),
    c("BF-B", "BF.B", "S&P 500"),
    c("BLDR", "BLDR", "S&P 500"),
    c("BG", "BG", "S&P 500"),
    c("BXP", "BXP", "S&P 500"),
    c("CHRW", "CHRW", "S&P 500"),
    c("CPT", "CPT", "S&P 500"),
    c("CPB", "CPB", "S&P 500"),
    c("COF", "COF", "S&P 500"),
    c("CAH", "CAH", "S&P 500"),
    c("CCL", "CCL", "S&P 500"),
    c("CARR", "CARR", "S&P 500"),
    c("CVNA", "CVNA", "S&P 500"),
    c("CASY", "CASY", "S&P 500"),
    c("CBOE", "CBOE", "S&P 500"),
    c("CBRE", "CBRE", "S&P 500"),
    c("CDW", "CDW", "S&P 500"),
    c("COR", "COR", "S&P 500"),
    c("CNC", "CNC", "S&P 500"),
    c("CNP", "CNP", "S&P 500"),
    c("CF", "CF", "S&P 500"),
    c("CRL", "CRL", "S&P 500"),
    c("CHTR", "CHTR", "S&P 500"),
    c("CHD", "CHD", "S&P 500"),
    c("CIEN", "CIEN", "S&P 500"),
    c("CI", "CI", "S&P 500"),
    c("CINF", "CINF", "S&P 500"),
    c("CSCO", "CSCO", "S&P 500"),
    c("C", "C", "S&P 500"),
    c("CFG", "CFG", "S&P 500"),
    c("CLX", "CLX", "S&P 500"),
    c("CMS", "CMS", "S&P 500"),
    c("CTSH", "CTSH", "S&P 500"),
    c("COHR", "COHR", "S&P 500"),
    c("COIN", "COIN", "S&P 500"),
    c("CMCSA", "CMCSA", "S&P 500"),
    c("FIX", "FIX", "S&P 500"),
    c("CAG", "CAG", "S&P 500"),
    c("ED", "ED", "S&P 500"),
    c("STZ", "STZ", "S&P 500"),
    c("CEG", "CEG", "S&P 500"),
    c("COO", "COO", "S&P 500"),
    c("CPRT", "CPRT", "S&P 500"),
    c("GLW", "GLW", "S&P 500"),
    c("CPAY", "CPAY", "S&P 500"),
    c("CTVA", "CTVA", "S&P 500"),
    c("CSGP", "CSGP", "S&P 500"),
    c("CRH", "CRH", "S&P 500"),
    c("CCI", "CCI", "S&P 500"),
    c("CVS", "CVS", "S&P 500"),
    c("DRI", "DRI", "S&P 500"),
    c("DDOG", "DDOG", "S&P 500"),
    c("DVA", "DVA", "S&P 500"),
    c("DECK", "DECK", "S&P 500"),
    c("DELL", "DELL", "S&P 500"),
    c("DAL", "DAL", "S&P 500"),
    c("DVN", "DVN", "S&P 500"),
    c("DXCM", "DXCM", "S&P 500"),
    c("FANG", "FANG", "S&P 500"),
    c("DLR", "DLR", "S&P 500"),
    c("DG", "DG", "S&P 500"),
    c("DLTR", "DLTR", "S&P 500"),
    c("D", "D", "S&P 500"),
    c("DPZ", "DPZ", "S&P 500"),
    c("DASH", "DASH", "S&P 500"),
    c("DOV", "DOV", "S&P 500"),
    c("DOW", "DOW", "S&P 500"),
    c("DHI", "DHI", "S&P 500"),
    c("DTE", "DTE", "S&P 500"),
    c("DD", "DD", "S&P 500"),
    c("EBAY", "EBAY", "S&P 500"),
    c("SATS", "SATS", "S&P 500"),
    c("EIX", "EIX", "S&P 500"),
    c("EA", "EA", "S&P 500"),
    c("EME", "EME", "S&P 500"),
    c("ETR", "ETR", "S&P 500"),
    c("EOG", "EOG", "S&P 500"),
    c("EPAM", "EPAM", "S&P 500"),
    c("EQT", "EQT", "S&P 500"),
    c("EFX", "EFX", "S&P 500"),
    c("EQIX", "EQIX", "S&P 500"),
    c("EQR", "EQR", "S&P 500"),
    c("ERIE", "ERIE", "S&P 500"),
    c("ESS", "ESS", "S&P 500"),
    c("EL", "EL", "S&P 500"),
    c("EG", "EG", "S&P 500"),
    c("EVRG", "EVRG", "S&P 500"),
    c("ES", "ES", "S&P 500"),
    c("EXC", "EXC", "S&P 500"),
    c("EXE", "EXE", "S&P 500"),
    c("EXPE", "EXPE", "S&P 500"),
    c("EXPD", "EXPD", "S&P 500"),
    c("EXR", "EXR", "S&P 500"),
    c("FFIV", "FFIV", "S&P 500"),
    c("FDS", "FDS", "S&P 500"),
    c("FICO", "FICO", "S&P 500"),
    c("FRT", "FRT", "S&P 500"),
    c("FIS", "FIS", "S&P 500"),
    c("FITB", "FITB", "S&P 500"),
    c("FSLR", "FSLR", "S&P 500"),
    c("FE", "FE", "S&P 500"),
    c("FISV", "FISV", "S&P 500"),
    c("F", "F", "S&P 500"),
    c("FTV", "FTV", "S&P 500"),
    c("FOXA", "FOXA", "S&P 500"),
    c("BEN", "BEN", "S&P 500"),
    c("FCX", "FCX", "S&P 500"),
    c("GRMN", "GRMN", "S&P 500"),
    c("IT", "IT", "S&P 500"),
    c("GEHC", "GEHC", "S&P 500"),
    c("GEV", "GEV", "S&P 500"),
    c("GEN", "GEN", "S&P 500"),
    c("GNRC", "GNRC", "S&P 500"),
    c("GM", "GM", "S&P 500"),
    c("GPC", "GPC", "S&P 500"),
    c("GPN", "GPN", "S&P 500"),
    c("GL", "GL", "S&P 500"),
    c("GDDY", "GDDY", "S&P 500"),
    c("HAL", "HAL", "S&P 500"),
    c("HIG", "HIG", "S&P 500"),
    c("HAS", "HAS", "S&P 500"),
    c("DOC", "DOC", "S&P 500"),
    c("HSIC", "HSIC", "S&P 500"),
    c("HPE", "HPE", "S&P 500"),
    c("HLT", "HLT", "S&P 500"),
    c("HRL", "HRL", "S&P 500"),
    c("HST", "HST", "S&P 500"),
    c("HWM", "HWM", "S&P 500"),
    c("HPQ", "HPQ", "S&P 500"),
    c("HUBB", "HUBB", "S&P 500"),
    c("HUM", "HUM", "S&P 500"),
    c("HBAN", "HBAN", "S&P 500"),
    c("HII", "HII", "S&P 500"),
    c("IBM", "IBM", "S&P 500"),
    c("IEX", "IEX", "S&P 500"),
    c("INCY", "INCY", "S&P 500"),
    c("IR", "IR", "S&P 500"),
    c("PODD", "PODD", "S&P 500"),
    c("INTC", "INTC", "S&P 500"),
    c("IBKR", "IBKR", "S&P 500"),
    c("IFF", "IFF", "S&P 500"),
    c("IP", "IP", "S&P 500"),
    c("IVZ", "IVZ", "S&P 500"),
    c("INVH", "INVH", "S&P 500"),
    c("IQV", "IQV", "S&P 500"),
    c("IRM", "IRM", "S&P 500"),
    c("JBHT", "JBHT", "S&P 500"),
    c("JBL", "JBL", "S&P 500"),
    c("JKHY", "JKHY", "S&P 500"),
    c("J", "J", "S&P 500"),
    c("JCI", "JCI", "S&P 500"),
    c("KVUE", "KVUE", "S&P 500"),
    c("KDP", "KDP", "S&P 500"),
    c("KEY", "KEY", "S&P 500"),
    c("KEYS", "KEYS", "S&P 500"),
    c("KIM", "KIM", "S&P 500"),
    c("KMI", "KMI", "S&P 500"),
    c("KHC", "KHC", "S&P 500"),
    c("KR", "KR", "S&P 500"),
    c("LHX", "LHX", "S&P 500"),
    c("LH", "LH", "S&P 500"),
    c("LVS", "LVS", "S&P 500"),
    c("LDOS", "LDOS", "S&P 500"),
    c("LEN", "LEN", "S&P 500"),
    c("LII", "LII", "S&P 500"),
    c("LYV", "LYV", "S&P 500"),
    c("L", "L", "S&P 500"),
    c("LITE", "LITE", "S&P 500"),
    c("LYB", "LYB", "S&P 500"),
    c("MTB", "MTB", "S&P 500"),
    c("MPC", "MPC", "S&P 500"),
    c("MAR", "MAR", "S&P 500"),
    c("MRSH", "MRSH", "S&P 500"),
    c("MLM", "MLM", "S&P 500"),
    c("MAS", "MAS", "S&P 500"),
    c("MKC", "MKC", "S&P 500"),
    c("MDT", "MDT", "S&P 500"),
    c("MET", "MET", "S&P 500"),
    c("MTD", "MTD", "S&P 500"),
    c("MGM", "MGM", "S&P 500"),
    c("MCHP", "MCHP", "S&P 500"),
    c("MAA", "MAA", "S&P 500"),
    c("MRNA", "MRNA", "S&P 500"),
    c("TAP", "TAP", "S&P 500"),
    c("MPWR", "MPWR", "S&P 500"),
    c("MOS", "MOS", "S&P 500"),
    c("MSI", "MSI", "S&P 500"),
    c("MSCI", "MSCI", "S&P 500"),
    c("NTAP", "NTAP", "S&P 500"),
    c("NEM", "NEM", "S&P 500"),
    c("NWSA", "NWSA", "S&P 500"),
    c("NI", "NI", "S&P 500"),
    c("NDSN", "NDSN", "S&P 500"),
    c("NTRS", "NTRS", "S&P 500"),
    c("NCLH", "NCLH", "S&P 500"),
    c("NRG", "NRG", "S&P 500"),
    c("NUE", "NUE", "S&P 500"),
    c("NVR", "NVR", "S&P 500"),
    c("NXPI", "NXPI", "S&P 500"),
    c("OXY", "OXY", "S&P 500"),
    c("ODFL", "ODFL", "S&P 500"),
    c("OMC", "OMC", "S&P 500"),
    c("ON", "ON", "S&P 500"),
    c("OKE", "OKE", "S&P 500"),
    c("OTIS", "OTIS", "S&P 500"),
    c("PKG", "PKG", "S&P 500"),
    c("PLTR", "PLTR", "S&P 500"),
    c("PSKY", "PSKY", "S&P 500"),
    c("PNR", "PNR", "S&P 500"),
    c("PFE", "PFE", "S&P 500"),
    c("PCG", "PCG", "S&P 500"),
    c("PSX", "PSX", "S&P 500"),
    c("PNW", "PNW", "S&P 500"),
    c("PNC", "PNC", "S&P 500"),
    c("POOL", "POOL", "S&P 500"),
    c("PPG", "PPG", "S&P 500"),
    c("PPL", "PPL", "S&P 500"),
    c("PFG", "PFG", "S&P 500"),
    c("PLD", "PLD", "S&P 500"),
    c("PRU", "PRU", "S&P 500"),
    c("PEG", "PEG", "S&P 500"),
    c("PTC", "PTC", "S&P 500"),
    c("PSA", "PSA", "S&P 500"),
    c("PHM", "PHM", "S&P 500"),
    c("PWR", "PWR", "S&P 500"),
    c("DGX", "DGX", "S&P 500"),
    c("RL", "RL", "S&P 500"),
    c("RJF", "RJF", "S&P 500"),
    c("O", "O", "S&P 500"),
    c("REG", "REG", "S&P 500"),
    c("RF", "RF", "S&P 500"),
    c("RMD", "RMD", "S&P 500"),
    c("RVTY", "RVTY", "S&P 500"),
    c("HOOD", "HOOD", "S&P 500"),
    c("ROK", "ROK", "S&P 500"),
    c("ROL", "ROL", "S&P 500"),
    c("RCL", "RCL", "S&P 500"),
    c("SNDK", "SNDK", "S&P 500"),
    c("SBAC", "SBAC", "S&P 500"),
    c("SLB", "SLB", "S&P 500"),
    c("STX", "STX", "S&P 500"),
    c("SRE", "SRE", "S&P 500"),
    c("SPG", "SPG", "S&P 500"),
    c("SWKS", "SWKS", "S&P 500"),
    c("SJM", "SJM", "S&P 500"),
    c("SW", "SW", "S&P 500"),
    c("SNA", "SNA", "S&P 500"),
    c("SOLV", "SOLV", "S&P 500"),
    c("LUV", "LUV", "S&P 500"),
    c("SWK", "SWK", "S&P 500"),
    c("STT", "STT", "S&P 500"),
    c("STLD", "STLD", "S&P 500"),
    c("STE", "STE", "S&P 500"),
    c("SMCI", "SMCI", "S&P 500"),
    c("SYF", "SYF", "S&P 500"),
    c("SYY", "SYY", "S&P 500"),
    c("TMUS", "TMUS", "S&P 500"),
    c("TROW", "TROW", "S&P 500"),
    c("TTWO", "TTWO", "S&P 500"),
    c("TPR", "TPR", "S&P 500"),
    c("TRGP", "TRGP", "S&P 500"),
    c("TEL", "TEL", "S&P 500"),
    c("TDY", "TDY", "S&P 500"),
    c("TER", "TER", "S&P 500"),
    c("TPL", "TPL", "S&P 500"),
    c("TXT", "TXT", "S&P 500"),
    c("TKO", "TKO", "S&P 500"),
    c("TTD", "TTD", "S&P 500"),
    c("TRMB", "TRMB", "S&P 500"),
    c("TFC", "TFC", "S&P 500"),
    c("TYL", "TYL", "S&P 500"),
    c("TSN", "TSN", "S&P 500"),
    c("USB", "USB", "S&P 500"),
    c("UDR", "UDR", "S&P 500"),
    c("ULTA", "ULTA", "S&P 500"),
    c("UAL", "UAL", "S&P 500"),
    c("URI", "URI", "S&P 500"),
    c("UHS", "UHS", "S&P 500"),
    c("VLO", "VLO", "S&P 500"),
    c("VEEV", "VEEV", "S&P 500"),
    c("VTR", "VTR", "S&P 500"),
    c("VLTO", "VLTO", "S&P 500"),
    c("VRSN", "VRSN", "S&P 500"),
    c("VRSK", "VRSK", "S&P 500"),
    c("VZ", "VZ", "S&P 500"),
    c("VRT", "VRT", "S&P 500"),
    c("VTRS", "VTRS", "S&P 500"),
    c("VICI", "VICI", "S&P 500"),
    c("VST", "VST", "S&P 500"),
    c("VMC", "VMC", "S&P 500"),
    c("WRB", "WRB", "S&P 500"),
    c("WAB", "WAB", "S&P 500"),
    c("WBD", "WBD", "S&P 500"),
    c("WAT", "WAT", "S&P 500"),
    c("WEC", "WEC", "S&P 500"),
    c("WELL", "WELL", "S&P 500"),
    c("WST", "WST", "S&P 500"),
    c("WDC", "WDC", "S&P 500"),
    c("WY", "WY", "S&P 500"),
    c("WSM", "WSM", "S&P 500"),
    c("WMB", "WMB", "S&P 500"),
    c("WTW", "WTW", "S&P 500"),
    c("WDAY", "WDAY", "S&P 500"),
    c("WYNN", "WYNN", "S&P 500"),
    c("XEL", "XEL", "S&P 500"),
    c("XYL", "XYL", "S&P 500"),
    c("ZBRA", "ZBRA", "S&P 500"),
    c("ZBH", "ZBH", "S&P 500"),
    c("AA", "AA", "S&P MidCap 400"),
    c("AAL", "AAL", "S&P MidCap 400"),
    c("AAON", "AAON", "S&P MidCap 400"),
    c("ACI", "ACI", "S&P MidCap 400"),
    c("ACM", "ACM", "S&P MidCap 400"),
    c("ADC", "ADC", "S&P MidCap 400"),
    c("AEIS", "AEIS", "S&P MidCap 400"),
    c("AFG", "AFG", "S&P MidCap 400"),
    c("AGCO", "AGCO", "S&P MidCap 400"),
    c("AHR", "AHR", "S&P MidCap 400"),
    c("AIT", "AIT", "S&P MidCap 400"),
    c("ALGM", "ALGM", "S&P MidCap 400"),
    c("ALK", "ALK", "S&P MidCap 400"),
    c("ALLY", "ALLY", "S&P MidCap 400"),
    c("ALV", "ALV", "S&P MidCap 400"),
    c("AM", "AM", "S&P MidCap 400"),
    c("AMG", "AMG", "S&P MidCap 400"),
    c("AMH", "AMH", "S&P MidCap 400"),
    c("AMKR", "AMKR", "S&P MidCap 400"),
    c("AN", "AN", "S&P MidCap 400"),
    c("ANF", "ANF", "S&P MidCap 400"),
    c("APG", "APG", "S&P MidCap 400"),
    c("APPF", "APPF", "S&P MidCap 400"),
    c("AR", "AR", "S&P MidCap 400"),
    c("ARMK", "ARMK", "S&P MidCap 400"),
    c("ARW", "ARW", "S&P MidCap 400"),
    c("ARWR", "ARWR", "S&P MidCap 400"),
    c("ASB", "ASB", "S&P MidCap 400"),
    c("ASH", "ASH", "S&P MidCap 400"),
    c("ATI", "ATI", "S&P MidCap 400"),
    c("ATR", "ATR", "S&P MidCap 400"),
    c("AVAV", "AVAV", "S&P MidCap 400"),
    c("AVNT", "AVNT", "S&P MidCap 400"),
    c("AVT", "AVT", "S&P MidCap 400"),
    c("AVTR", "AVTR", "S&P MidCap 400"),
    c("AXTA", "AXTA", "S&P MidCap 400"),
    c("AYI", "AYI", "S&P MidCap 400"),
    c("BAH", "BAH", "S&P MidCap 400"),
    c("BBWI", "BBWI", "S&P MidCap 400"),
    c("BC", "BC", "S&P MidCap 400"),
    c("BCO", "BCO", "S&P MidCap 400"),
    c("BDC", "BDC", "S&P MidCap 400"),
    c("BHF", "BHF", "S&P MidCap 400"),
    c("BILL", "BILL", "S&P MidCap 400"),
    c("BIO", "BIO", "S&P MidCap 400"),
    c("BJ", "BJ", "S&P MidCap 400"),
    c("BKH", "BKH", "S&P MidCap 400"),
    c("BLD", "BLD", "S&P MidCap 400"),
    c("BLKB", "BLKB", "S&P MidCap 400"),
    c("BMRN", "BMRN", "S&P MidCap 400"),
    c("BRBR", "BRBR", "S&P MidCap 400"),
    c("BRKR", "BRKR", "S&P MidCap 400"),
    c("BROS", "BROS", "S&P MidCap 400"),
    c("BRX", "BRX", "S&P MidCap 400"),
    c("BSY", "BSY", "S&P MidCap 400"),
    c("BURL", "BURL", "S&P MidCap 400"),
    c("BWA", "BWA", "S&P MidCap 400"),
    c("BWXT", "BWXT", "S&P MidCap 400"),
    c("BYD", "BYD", "S&P MidCap 400"),
    c("CACI", "CACI", "S&P MidCap 400"),
    c("CAR", "CAR", "S&P MidCap 400"),
    c("CART", "CART", "S&P MidCap 400"),
    c("CAVA", "CAVA", "S&P MidCap 400"),
    c("CBSH", "CBSH", "S&P MidCap 400"),
    c("CBT", "CBT", "S&P MidCap 400"),
    c("CCK", "CCK", "S&P MidCap 400"),
    c("CDP", "CDP", "S&P MidCap 400"),
    c("CELH", "CELH", "S&P MidCap 400"),
    c("CFR", "CFR", "S&P MidCap 400"),
    c("CG", "CG", "S&P MidCap 400"),
    c("CGNX", "CGNX", "S&P MidCap 400"),
    c("CHDN", "CHDN", "S&P MidCap 400"),
    c("CHE", "CHE", "S&P MidCap 400"),
    c("CHH", "CHH", "S&P MidCap 400"),
    c("CHRD", "CHRD", "S&P MidCap 400"),
    c("CHWY", "CHWY", "S&P MidCap 400"),
    c("CLF", "CLF", "S&P MidCap 400"),
    c("CLH", "CLH", "S&P MidCap 400"),
    c("CMC", "CMC", "S&P MidCap 400"),
    c("CNH", "CNH", "S&P MidCap 400"),
    c("CNM", "CNM", "S&P MidCap 400"),
    c("CNO", "CNO", "S&P MidCap 400"),
    c("CNX", "CNX", "S&P MidCap 400"),
    c("CNXC", "CNXC", "S&P MidCap 400"),
    c("COKE", "COKE", "S&P MidCap 400"),
    c("COLB", "COLB", "S&P MidCap 400"),
    c("COLM", "COLM", "S&P MidCap 400"),
    c("COTY", "COTY", "S&P MidCap 400"),
    c("CPRI", "CPRI", "S&P MidCap 400"),
    c("CR", "CR", "S&P MidCap 400"),
    c("CRBG", "CRBG", "S&P MidCap 400"),
    c("CROX", "CROX", "S&P MidCap 400"),
    c("CRS", "CRS", "S&P MidCap 400"),
    c("CRUS", "CRUS", "S&P MidCap 400"),
    c("CSL", "CSL", "S&P MidCap 400"),
    c("CTRE", "CTRE", "S&P MidCap 400"),
    c("CUBE", "CUBE", "S&P MidCap 400"),
    c("CUZ", "CUZ", "S&P MidCap 400"),
    c("CVLT", "CVLT", "S&P MidCap 400"),
    c("CW", "CW", "S&P MidCap 400"),
    c("CXT", "CXT", "S&P MidCap 400"),
    c("CYTK", "CYTK", "S&P MidCap 400"),
    c("DAR", "DAR", "S&P MidCap 400"),
    c("DBX", "DBX", "S&P MidCap 400"),
    c("DCI", "DCI", "S&P MidCap 400"),
    c("DINO", "DINO", "S&P MidCap 400"),
    c("DKS", "DKS", "S&P MidCap 400"),
    c("DLB", "DLB", "S&P MidCap 400"),
    c("DOCN", "DOCN", "S&P MidCap 400"),
    c("DOCS", "DOCS", "S&P MidCap 400"),
    c("DOCU", "DOCU", "S&P MidCap 400"),
    c("DT", "DT", "S&P MidCap 400"),
    c("DTM", "DTM", "S&P MidCap 400"),
    c("DUOL", "DUOL", "S&P MidCap 400"),
    c("DY", "DY", "S&P MidCap 400"),
    c("EEFT", "EEFT", "S&P MidCap 400"),
    c("EGP", "EGP", "S&P MidCap 400"),
    c("EHC", "EHC", "S&P MidCap 400"),
    c("ELAN", "ELAN", "S&P MidCap 400"),
    c("ELF", "ELF", "S&P MidCap 400"),
    c("ELS", "ELS", "S&P MidCap 400"),
    c("ENS", "ENS", "S&P MidCap 400"),
    c("ENSG", "ENSG", "S&P MidCap 400"),
    c("ENTG", "ENTG", "S&P MidCap 400"),
    c("EPR", "EPR", "S&P MidCap 400"),
    c("EQH", "EQH", "S&P MidCap 400"),
    c("ESAB", "ESAB", "S&P MidCap 400"),
    c("ESNT", "ESNT", "S&P MidCap 400"),
    c("EVR", "EVR", "S&P MidCap 400"),
    c("EWBC", "EWBC", "S&P MidCap 400"),
    c("EXEL", "EXEL", "S&P MidCap 400"),
    c("EXLS", "EXLS", "S&P MidCap 400"),
    c("EXP", "EXP", "S&P MidCap 400"),
    c("EXPO", "EXPO", "S&P MidCap 400"),
    c("FAF", "FAF", "S&P MidCap 400"),
    c("FBIN", "FBIN", "S&P MidCap 400"),
    c("FCFS", "FCFS", "S&P MidCap 400"),
    c("FCN", "FCN", "S&P MidCap 400"),
    c("FFIN", "FFIN", "S&P MidCap 400"),
    c("FHI", "FHI", "S&P MidCap 400"),
    c("FHN", "FHN", "S&P MidCap 400"),
    c("FIVE", "FIVE", "S&P MidCap 400"),
    c("FLEX", "FLEX", "S&P MidCap 400"),
    c("FLG", "FLG", "S&P MidCap 400"),
    c("FLO", "FLO", "S&P MidCap 400"),
    c("FLR", "FLR", "S&P MidCap 400"),
    c("FLS", "FLS", "S&P MidCap 400"),
    c("FN", "FN", "S&P MidCap 400"),
    c("FNB", "FNB", "S&P MidCap 400"),
    c("FND", "FND", "S&P MidCap 400"),
    c("FNF", "FNF", "S&P MidCap 400"),
    c("FOUR", "FOUR", "S&P MidCap 400"),
    c("FR", "FR", "S&P MidCap 400"),
    c("FTI", "FTI", "S&P MidCap 400"),
    c("G", "G", "S&P MidCap 400"),
    c("GAP", "GAP", "S&P MidCap 400"),
    c("GATX", "GATX", "S&P MidCap 400"),
    c("GBCI", "GBCI", "S&P MidCap 400"),
    c("GEF", "GEF", "S&P MidCap 400"),
    c("GGG", "GGG", "S&P MidCap 400"),
    c("GHC", "GHC", "S&P MidCap 400"),
    c("GLPI", "GLPI", "S&P MidCap 400"),
    c("GME", "GME", "S&P MidCap 400"),
    c("GMED", "GMED", "S&P MidCap 400"),
    c("GNTX", "GNTX", "S&P MidCap 400"),
    c("GPK", "GPK", "S&P MidCap 400"),
    c("GT", "GT", "S&P MidCap 400"),
    c("GTLS", "GTLS", "S&P MidCap 400"),
    c("GWRE", "GWRE", "S&P MidCap 400"),
    c("GXO", "GXO", "S&P MidCap 400"),
    c("H", "H", "S&P MidCap 400"),
    c("HAE", "HAE", "S&P MidCap 400"),
    c("HALO", "HALO", "S&P MidCap 400"),
    c("HGV", "HGV", "S&P MidCap 400"),
    c("HIMS", "HIMS", "S&P MidCap 400"),
    c("HL", "HL", "S&P MidCap 400"),
    c("HLI", "HLI", "S&P MidCap 400"),
    c("HLNE", "HLNE", "S&P MidCap 400"),
    c("HOG", "HOG", "S&P MidCap 400"),
    c("HOMB", "HOMB", "S&P MidCap 400"),
    c("HQY", "HQY", "S&P MidCap 400"),
    c("HR", "HR", "S&P MidCap 400"),
    c("HRB", "HRB", "S&P MidCap 400"),
    c("HWC", "HWC", "S&P MidCap 400"),
    c("HXL", "HXL", "S&P MidCap 400"),
    c("IBOC", "IBOC", "S&P MidCap 400"),
    c("IDA", "IDA", "S&P MidCap 400"),
    c("IDCC", "IDCC", "S&P MidCap 400"),
    c("ILMN", "ILMN", "S&P MidCap 400"),
    c("INGR", "INGR", "S&P MidCap 400"),
    c("IPGP", "IPGP", "S&P MidCap 400"),
    c("IRT", "IRT", "S&P MidCap 400"),
    c("ITT", "ITT", "S&P MidCap 400"),
    c("JAZZ", "JAZZ", "S&P MidCap 400"),
    c("JEF", "JEF", "S&P MidCap 400"),
    c("JHG", "JHG", "S&P MidCap 400"),
    c("JLL", "JLL", "S&P MidCap 400"),
    c("KBH", "KBH", "S&P MidCap 400"),
    c("KBR", "KBR", "S&P MidCap 400"),
    c("KD", "KD", "S&P MidCap 400"),
    c("KEX", "KEX", "S&P MidCap 400"),
    c("KNF", "KNF", "S&P MidCap 400"),
    c("KNSL", "KNSL", "S&P MidCap 400"),
    c("KNX", "KNX", "S&P MidCap 400"),
    c("KRC", "KRC", "S&P MidCap 400"),
    c("KRG", "KRG", "S&P MidCap 400"),
    c("KTOS", "KTOS", "S&P MidCap 400"),
    c("LAD", "LAD", "S&P MidCap 400"),
    c("LAMR", "LAMR", "S&P MidCap 400"),
    c("LEA", "LEA", "S&P MidCap 400"),
    c("LECO", "LECO", "S&P MidCap 400"),
    c("LFUS", "LFUS", "S&P MidCap 400"),
    c("LIVN", "LIVN", "S&P MidCap 400"),
    c("LNTH", "LNTH", "S&P MidCap 400"),
    c("LOPE", "LOPE", "S&P MidCap 400"),
    c("LPX", "LPX", "S&P MidCap 400"),
    c("LSCC", "LSCC", "S&P MidCap 400"),
    c("LSTR", "LSTR", "S&P MidCap 400"),
    c("M", "M", "S&P MidCap 400"),
    c("MANH", "MANH", "S&P MidCap 400"),
    c("MASI", "MASI", "S&P MidCap 400"),
    c("MAT", "MAT", "S&P MidCap 400"),
    c("MEDP", "MEDP", "S&P MidCap 400"),
    c("MIDD", "MIDD", "S&P MidCap 400"),
    c("MKSI", "MKSI", "S&P MidCap 400"),
    c("MLI", "MLI", "S&P MidCap 400"),
    c("MMS", "MMS", "S&P MidCap 400"),
    c("MOG-A", "MOG.A", "S&P MidCap 400"),
    c("MORN", "MORN", "S&P MidCap 400"),
    c("MP", "MP", "S&P MidCap 400"),
    c("MSA", "MSA", "S&P MidCap 400"),
    c("MSM", "MSM", "S&P MidCap 400"),
    c("MTDR", "MTDR", "S&P MidCap 400"),
    c("MTG", "MTG", "S&P MidCap 400"),
    c("MTN", "MTN", "S&P MidCap 400"),
    c("MTSI", "MTSI", "S&P MidCap 400"),
    c("MTZ", "MTZ", "S&P MidCap 400"),
    c("MUR", "MUR", "S&P MidCap 400"),
    c("MUSA", "MUSA", "S&P MidCap 400"),
    c("MZTI", "MZTI", "S&P MidCap 400"),
    c("NBIX", "NBIX", "S&P MidCap 400"),
    c("NEU", "NEU", "S&P MidCap 400"),
    c("NFG", "NFG", "S&P MidCap 400"),
    c("NJR", "NJR", "S&P MidCap 400"),
    c("NLY", "NLY", "S&P MidCap 400"),
    c("NNN", "NNN", "S&P MidCap 400"),
    c("NOV", "NOV", "S&P MidCap 400"),
    c("NOVT", "NOVT", "S&P MidCap 400"),
    c("NSA", "NSA", "S&P MidCap 400"),
    c("NTNX", "NTNX", "S&P MidCap 400"),
    c("NVST", "NVST", "S&P MidCap 400"),
    c("NVT", "NVT", "S&P MidCap 400"),
    c("NWE", "NWE", "S&P MidCap 400"),
    c("NXST", "NXST", "S&P MidCap 400"),
    c("NXT", "NXT", "S&P MidCap 400"),
    c("NYT", "NYT", "S&P MidCap 400"),
    c("OC", "OC", "S&P MidCap 400"),
    c("OGE", "OGE", "S&P MidCap 400"),
    c("OGS", "OGS", "S&P MidCap 400"),
    c("OHI", "OHI", "S&P MidCap 400"),
    c("OKTA", "OKTA", "S&P MidCap 400"),
    c("OLED", "OLED", "S&P MidCap 400"),
    c("OLLI", "OLLI", "S&P MidCap 400"),
    c("OLN", "OLN", "S&P MidCap 400"),
    c("ONB", "ONB", "S&P MidCap 400"),
    c("ONTO", "ONTO", "S&P MidCap 400"),
    c("OPCH", "OPCH", "S&P MidCap 400"),
    c("ORA", "ORA", "S&P MidCap 400"),
    c("ORI", "ORI", "S&P MidCap 400"),
    c("OSK", "OSK", "S&P MidCap 400"),
    c("OVV", "OVV", "S&P MidCap 400"),
    c("OZK", "OZK", "S&P MidCap 400"),
    c("PAG", "PAG", "S&P MidCap 400"),
    c("PATH", "PATH", "S&P MidCap 400"),
    c("PB", "PB", "S&P MidCap 400"),
    c("PBF", "PBF", "S&P MidCap 400"),
    c("PCTY", "PCTY", "S&P MidCap 400"),
    c("PEGA", "PEGA", "S&P MidCap 400"),
    c("PEN", "PEN", "S&P MidCap 400"),
    c("PFGC", "PFGC", "S&P MidCap 400"),
    c("PII", "PII", "S&P MidCap 400"),
    c("PINS", "PINS", "S&P MidCap 400"),
    c("PK", "PK", "S&P MidCap 400"),
    c("PLNT", "PLNT", "S&P MidCap 400"),
    c("PNFP", "PNFP", "S&P MidCap 400"),
    c("POR", "POR", "S&P MidCap 400"),
    c("POST", "POST", "S&P MidCap 400"),
    c("PPC", "PPC", "S&P MidCap 400"),
    c("PR", "PR", "S&P MidCap 400"),
    c("PRI", "PRI", "S&P MidCap 400"),
    c("PSN", "PSN", "S&P MidCap 400"),
    c("PSTG", "PSTG", "S&P MidCap 400"),
    c("PVH", "PVH", "S&P MidCap 400"),
    c("QLYS", "QLYS", "S&P MidCap 400"),
    c("R", "R", "S&P MidCap 400"),
    c("RBA", "RBA", "S&P MidCap 400"),
    c("RBC", "RBC", "S&P MidCap 400"),
    c("REXR", "REXR", "S&P MidCap 400"),
    c("RGA", "RGA", "S&P MidCap 400"),
    c("RGEN", "RGEN", "S&P MidCap 400"),
    c("RGLD", "RGLD", "S&P MidCap 400"),
    c("RH", "RH", "S&P MidCap 400"),
    c("RLI", "RLI", "S&P MidCap 400"),
    c("RMBS", "RMBS", "S&P MidCap 400"),
    c("RNR", "RNR", "S&P MidCap 400"),
    c("ROIV", "ROIV", "S&P MidCap 400"),
    c("RPM", "RPM", "S&P MidCap 400"),
    c("RRC", "RRC", "S&P MidCap 400"),
    c("RRX", "RRX", "S&P MidCap 400"),
    c("RS", "RS", "S&P MidCap 400"),
    c("RYAN", "RYAN", "S&P MidCap 400"),
    c("RYN", "RYN", "S&P MidCap 400"),
    c("SAIA", "SAIA", "S&P MidCap 400"),
    c("SAIC", "SAIC", "S&P MidCap 400"),
    c("SAM", "SAM", "S&P MidCap 400"),
    c("SARO", "SARO", "S&P MidCap 400"),
    c("SBRA", "SBRA", "S&P MidCap 400"),
    c("SCI", "SCI", "S&P MidCap 400"),
    c("SEIC", "SEIC", "S&P MidCap 400"),
    c("SF", "SF", "S&P MidCap 400"),
    c("SFM", "SFM", "S&P MidCap 400"),
    c("SGI", "SGI", "S&P MidCap 400"),
    c("SHC", "SHC", "S&P MidCap 400"),
    c("SIGI", "SIGI", "S&P MidCap 400"),
    c("SITM", "SITM", "S&P MidCap 400"),
    c("SLAB", "SLAB", "S&P MidCap 400"),
    c("SLGN", "SLGN", "S&P MidCap 400"),
    c("SLM", "SLM", "S&P MidCap 400"),
    c("SMG", "SMG", "S&P MidCap 400"),
    c("SNX", "SNX", "S&P MidCap 400"),
    c("SOLS", "SOLS", "S&P MidCap 400"),
    c("SON", "SON", "S&P MidCap 400"),
    c("SPXC", "SPXC", "S&P MidCap 400"),
    c("SR", "SR", "S&P MidCap 400"),
    c("SSB", "SSB", "S&P MidCap 400"),
    c("SSD", "SSD", "S&P MidCap 400"),
    c("ST", "ST", "S&P MidCap 400"),
    c("STAG", "STAG", "S&P MidCap 400"),
    c("STRL", "STRL", "S&P MidCap 400"),
    c("STWD", "STWD", "S&P MidCap 400"),
    c("SWX", "SWX", "S&P MidCap 400"),
    c("SYNA", "SYNA", "S&P MidCap 400"),
    c("TCBI", "TCBI", "S&P MidCap 400"),
    c("TEX", "TEX", "S&P MidCap 400"),
    c("THC", "THC", "S&P MidCap 400"),
    c("THG", "THG", "S&P MidCap 400"),
    c("THO", "THO", "S&P MidCap 400"),
    c("TKR", "TKR", "S&P MidCap 400"),
    c("TLN", "TLN", "S&P MidCap 400"),
    c("TMHC", "TMHC", "S&P MidCap 400"),
    c("TNL", "TNL", "S&P MidCap 400"),
    c("TOL", "TOL", "S&P MidCap 400"),
    c("TREX", "TREX", "S&P MidCap 400"),
    c("TRU", "TRU", "S&P MidCap 400"),
    c("TTC", "TTC", "S&P MidCap 400"),
    c("TTEK", "TTEK", "S&P MidCap 400"),
    c("TTMI", "TTMI", "S&P MidCap 400"),
    c("TWLO", "TWLO", "S&P MidCap 400"),
    c("TXNM", "TXNM", "S&P MidCap 400"),
    c("TXRH", "TXRH", "S&P MidCap 400"),
    c("UBSI", "UBSI", "S&P MidCap 400"),
    c("UFPI", "UFPI", "S&P MidCap 400"),
    c("UGI", "UGI", "S&P MidCap 400"),
    c("ULS", "ULS", "S&P MidCap 400"),
    c("UMBF", "UMBF", "S&P MidCap 400"),
    c("UNM", "UNM", "S&P MidCap 400"),
    c("USFD", "USFD", "S&P MidCap 400"),
    c("UTHR", "UTHR", "S&P MidCap 400"),
    c("VAL", "VAL", "S&P MidCap 400"),
    c("VC", "VC", "S&P MidCap 400"),
    c("VFC", "VFC", "S&P MidCap 400"),
    c("VICR", "VICR", "S&P MidCap 400"),
    c("VLY", "VLY", "S&P MidCap 400"),
    c("VMI", "VMI", "S&P MidCap 400"),
    c("VNO", "VNO", "S&P MidCap 400"),
    c("VNOM", "VNOM", "S&P MidCap 400"),
    c("VNT", "VNT", "S&P MidCap 400"),
    c("VOYA", "VOYA", "S&P MidCap 400"),
    c("VVV", "VVV", "S&P MidCap 400"),
    c("WAL", "WAL", "S&P MidCap 400"),
    c("WBS", "WBS", "S&P MidCap 400"),
    c("WCC", "WCC", "S&P MidCap 400"),
    c("WEX", "WEX", "S&P MidCap 400"),
    c("WFRD", "WFRD", "S&P MidCap 400"),
    c("WH", "WH", "S&P MidCap 400"),
    c("WHR", "WHR", "S&P MidCap 400"),
    c("WING", "WING", "S&P MidCap 400"),
    c("WLK", "WLK", "S&P MidCap 400"),
    c("WMG", "WMG", "S&P MidCap 400"),
    c("WMS", "WMS", "S&P MidCap 400"),
    c("WPC", "WPC", "S&P MidCap 400"),
    c("WSO", "WSO", "S&P MidCap 400"),
    c("WTFC", "WTFC", "S&P MidCap 400"),
    c("WTRG", "WTRG", "S&P MidCap 400"),
    c("WTS", "WTS", "S&P MidCap 400"),
    c("WWD", "WWD", "S&P MidCap 400"),
    c("XPO", "XPO", "S&P MidCap 400"),
    c("XRAY", "XRAY", "S&P MidCap 400"),
    c("YETI", "YETI", "S&P MidCap 400"),
    c("ZION", "ZION", "S&P MidCap 400"),
  ],
};

export const UNIVERSE_COUNTRIES: UniverseCountry[] = ["India", "Canada", "United States"];

/** Candidates for a country, excluding symbols already held (case-insensitive). */
export function candidatesFor(country: UniverseCountry, heldSymbols: Iterable<string>): CandidateStock[] {
  const held = new Set([...heldSymbols].map((s) => s.toUpperCase().trim()));
  return UNIVERSES[country].filter((x) => !held.has(x.symbol.toUpperCase()));
}

/** Parse a user-pasted list of symbols (commas / spaces / newlines) into candidates. */
export function parseCustomSymbols(text: string, heldSymbols: Iterable<string>): CandidateStock[] {
  const held = new Set([...heldSymbols].map((s) => s.toUpperCase().trim()));
  const seen = new Set<string>();
  const out: CandidateStock[] = [];
  for (const raw of text.split(/[\s,;]+/)) {
    const s = raw.trim().toUpperCase();
    if (!s || s.length > 20 || !/^[A-Z0-9][A-Z0-9.&^=-]*$/.test(s)) continue;
    if (held.has(s) || seen.has(s)) continue;
    seen.add(s);
    out.push({ symbol: s, name: s, sector: "—" });
    if (out.length >= 100) break;
  }
  return out;
}
