/**
 * Scan universes — broad, hand-curated coverage of each market's widely-traded
 * names (large caps + prominent mid caps), so screens see close to the whole
 * investable landscape without any paid screener API.
 *
 * NOT recommendations — candidates. The same scorecard that judges your
 * holdings judges them, live, from free Yahoo data. Names that fail to fetch
 * are reported and skipped. Edit freely — anything with a Yahoo symbol works,
 * and the Screeners tab also accepts a pasted custom list.
 */

export interface CandidateStock {
  symbol: string; // Yahoo symbol
  name: string;
  sector: string; // display hint only; live sector comes from Yahoo
}

export type UniverseCountry = "India" | "Canada" | "United States";

const c = (symbol: string, name: string, sector: string): CandidateStock => ({ symbol, name, sector });

export const UNIVERSES: Record<UniverseCountry, CandidateStock[]> = {
  India: [
    // — IT & tech services —
    c("TCS.NS", "Tata Consultancy Services", "IT Services"),
    c("INFY.NS", "Infosys", "IT Services"),
    c("HCLTECH.NS", "HCL Technologies", "IT Services"),
    c("WIPRO.NS", "Wipro", "IT Services"),
    c("TECHM.NS", "Tech Mahindra", "IT Services"),
    c("LTIM.NS", "LTIMindtree", "IT Services"),
    c("PERSISTENT.NS", "Persistent Systems", "IT Services"),
    c("COFORGE.NS", "Coforge", "IT Services"),
    c("MPHASIS.NS", "Mphasis", "IT Services"),
    c("LTTS.NS", "L&T Technology Services", "ER&D Services"),
    c("TATAELXSI.NS", "Tata Elxsi", "Design / ER&D"),
    c("KPITTECH.NS", "KPIT Technologies", "Auto Software"),
    c("OFSS.NS", "Oracle Financial Services", "Banking Software"),
    c("NAUKRI.NS", "Info Edge (Naukri)", "Internet"),
    c("POLICYBZR.NS", "PB Fintech (Policybazaar)", "Internet / Fintech"),
    c("IRCTC.NS", "IRCTC", "Internet / Travel"),
    // — banks & NBFCs —
    c("HDFCBANK.NS", "HDFC Bank", "Banks"),
    c("ICICIBANK.NS", "ICICI Bank", "Banks"),
    c("KOTAKBANK.NS", "Kotak Mahindra Bank", "Banks"),
    c("AXISBANK.NS", "Axis Bank", "Banks"),
    c("SBIN.NS", "State Bank of India", "Banks"),
    c("INDUSINDBK.NS", "IndusInd Bank", "Banks"),
    c("FEDERALBNK.NS", "Federal Bank", "Banks"),
    c("IDFCFIRSTB.NS", "IDFC FIRST Bank", "Banks"),
    c("BAJFINANCE.NS", "Bajaj Finance", "NBFC"),
    c("BAJAJFINSV.NS", "Bajaj Finserv", "Financial Services"),
    c("CHOLAFIN.NS", "Cholamandalam Finance", "NBFC"),
    c("SHRIRAMFIN.NS", "Shriram Finance", "NBFC"),
    c("MUTHOOTFIN.NS", "Muthoot Finance", "Gold NBFC"),
    c("PFC.NS", "Power Finance Corp", "Infra Finance"),
    c("RECLTD.NS", "REC Ltd", "Infra Finance"),
    // — insurance & capital markets —
    c("HDFCLIFE.NS", "HDFC Life Insurance", "Insurance"),
    c("SBILIFE.NS", "SBI Life Insurance", "Insurance"),
    c("ICICIPRULI.NS", "ICICI Prudential Life", "Insurance"),
    c("ICICIGI.NS", "ICICI Lombard", "General Insurance"),
    c("LICI.NS", "Life Insurance Corp", "Insurance"),
    c("HDFCAMC.NS", "HDFC AMC", "Asset Management"),
    c("CAMS.NS", "CAMS", "Capital-market Infra"),
    c("CDSL.NS", "CDSL", "Depository"),
    c("BSE.NS", "BSE Ltd", "Exchange"),
    c("MCX.NS", "MCX", "Exchange"),
    c("IEX.NS", "Indian Energy Exchange", "Exchange"),
    c("ANGELONE.NS", "Angel One", "Broking"),
    // — consumer staples —
    c("HINDUNILVR.NS", "Hindustan Unilever", "FMCG"),
    c("NESTLEIND.NS", "Nestlé India", "FMCG"),
    c("ITC.NS", "ITC", "FMCG / Tobacco"),
    c("BRITANNIA.NS", "Britannia", "FMCG"),
    c("DABUR.NS", "Dabur", "FMCG"),
    c("MARICO.NS", "Marico", "FMCG"),
    c("GODREJCP.NS", "Godrej Consumer", "FMCG"),
    c("COLPAL.NS", "Colgate-Palmolive India", "FMCG"),
    c("TATACONSUM.NS", "Tata Consumer Products", "FMCG"),
    c("VBL.NS", "Varun Beverages", "Beverages"),
    c("UBL.NS", "United Breweries", "Beverages"),
    c("UNITDSPR.NS", "United Spirits", "Beverages"),
    c("PGHH.NS", "P&G Hygiene & Health", "FMCG"),
    c("JUBLFOOD.NS", "Jubilant FoodWorks", "QSR"),
    // — retail & consumer discretionary —
    c("DMART.NS", "Avenue Supermarts (DMart)", "Retail"),
    c("TRENT.NS", "Trent (Westside/Zudio)", "Retail"),
    c("TITAN.NS", "Titan Company", "Jewellery / Retail"),
    c("PAGEIND.NS", "Page Industries (Jockey)", "Apparel"),
    c("BATAINDIA.NS", "Bata India", "Footwear"),
    c("DIXON.NS", "Dixon Technologies", "Electronics Mfg"),
    c("VOLTAS.NS", "Voltas", "Durables"),
    c("BLUESTARCO.NS", "Blue Star", "Durables"),
    c("CROMPTON.NS", "Crompton Greaves CE", "Durables"),
    c("HAVELLS.NS", "Havells India", "Electricals"),
    c("POLYCAB.NS", "Polycab India", "Cables"),
    c("KEI.NS", "KEI Industries", "Cables"),
    c("INDHOTEL.NS", "Indian Hotels (Taj)", "Hotels"),
    c("INDIGO.NS", "InterGlobe Aviation (IndiGo)", "Airlines"),
    // — autos & ancillaries —
    c("MARUTI.NS", "Maruti Suzuki", "Autos"),
    c("M&M.NS", "Mahindra & Mahindra", "Autos"),
    c("TATAMOTORS.NS", "Tata Motors", "Autos"),
    c("BAJAJ-AUTO.NS", "Bajaj Auto", "2-Wheelers"),
    c("EICHERMOT.NS", "Eicher Motors (Royal Enfield)", "2-Wheelers"),
    c("TVSMOTOR.NS", "TVS Motor", "2-Wheelers"),
    c("HEROMOTOCO.NS", "Hero MotoCorp", "2-Wheelers"),
    c("ASHOKLEY.NS", "Ashok Leyland", "Commercial Vehicles"),
    c("MOTHERSON.NS", "Samvardhana Motherson", "Auto Parts"),
    c("BHARATFORG.NS", "Bharat Forge", "Auto Parts / Forging"),
    c("BALKRISIND.NS", "Balkrishna Industries", "Tyres"),
    c("MRF.NS", "MRF", "Tyres"),
    c("APOLLOTYRE.NS", "Apollo Tyres", "Tyres"),
    c("TIINDIA.NS", "Tube Investments", "Auto / Engineering"),
    c("BOSCHLTD.NS", "Bosch India", "Auto Parts"),
    // — pharma & healthcare —
    c("SUNPHARMA.NS", "Sun Pharma", "Pharma"),
    c("DRREDDY.NS", "Dr. Reddy's", "Pharma"),
    c("CIPLA.NS", "Cipla", "Pharma"),
    c("DIVISLAB.NS", "Divi's Laboratories", "Pharma API"),
    c("TORNTPHARM.NS", "Torrent Pharma", "Pharma"),
    c("LUPIN.NS", "Lupin", "Pharma"),
    c("AUROPHARMA.NS", "Aurobindo Pharma", "Pharma"),
    c("ALKEM.NS", "Alkem Laboratories", "Pharma"),
    c("ZYDUSLIFE.NS", "Zydus Lifesciences", "Pharma"),
    c("IPCALAB.NS", "Ipca Laboratories", "Pharma"),
    c("ABBOTINDIA.NS", "Abbott India", "Pharma MNC"),
    c("BIOCON.NS", "Biocon", "Biotech"),
    c("SYNGENE.NS", "Syngene International", "CRO"),
    c("LAURUSLABS.NS", "Laurus Labs", "Pharma API"),
    c("APOLLOHOSP.NS", "Apollo Hospitals", "Hospitals"),
    c("MAXHEALTH.NS", "Max Healthcare", "Hospitals"),
    c("FORTIS.NS", "Fortis Healthcare", "Hospitals"),
    c("LALPATHLAB.NS", "Dr Lal PathLabs", "Diagnostics"),
    // — energy, utilities, commodities —
    c("RELIANCE.NS", "Reliance Industries", "Conglomerate / Energy"),
    c("ONGC.NS", "ONGC", "Oil & Gas"),
    c("IOC.NS", "Indian Oil", "Refining"),
    c("BPCL.NS", "BPCL", "Refining"),
    c("GAIL.NS", "GAIL", "Gas Utility"),
    c("NTPC.NS", "NTPC", "Power"),
    c("POWERGRID.NS", "Power Grid", "Transmission"),
    c("TATAPOWER.NS", "Tata Power", "Power"),
    c("COALINDIA.NS", "Coal India", "Mining"),
    c("JSWSTEEL.NS", "JSW Steel", "Steel"),
    c("TATASTEEL.NS", "Tata Steel", "Steel"),
    c("HINDALCO.NS", "Hindalco", "Aluminium"),
    c("VEDL.NS", "Vedanta", "Diversified Mining"),
    // — industrials, infra, defence —
    c("LT.NS", "Larsen & Toubro", "E&C"),
    c("SIEMENS.NS", "Siemens India", "Capital Goods"),
    c("ABB.NS", "ABB India", "Capital Goods"),
    c("CGPOWER.NS", "CG Power", "Capital Goods"),
    c("THERMAX.NS", "Thermax", "Capital Goods"),
    c("CUMMINSIND.NS", "Cummins India", "Engines"),
    c("HAL.NS", "Hindustan Aeronautics", "Defence"),
    c("BEL.NS", "Bharat Electronics", "Defence"),
    c("ADANIENT.NS", "Adani Enterprises", "Conglomerate"),
    c("ADANIPORTS.NS", "Adani Ports", "Ports"),
    c("BHARTIARTL.NS", "Bharti Airtel", "Telecom"),
    c("TATACOMM.NS", "Tata Communications", "Telecom Infra"),
    // — cement, chemicals, materials —
    c("ULTRACEMCO.NS", "UltraTech Cement", "Cement"),
    c("SHREECEM.NS", "Shree Cement", "Cement"),
    c("AMBUJACEM.NS", "Ambuja Cements", "Cement"),
    c("JKCEMENT.NS", "JK Cement", "Cement"),
    c("DALBHARAT.NS", "Dalmia Bharat", "Cement"),
    c("GRASIM.NS", "Grasim Industries", "Cement / Chemicals"),
    c("ASIANPAINT.NS", "Asian Paints", "Paints"),
    c("BERGEPAINT.NS", "Berger Paints", "Paints"),
    c("PIDILITIND.NS", "Pidilite Industries", "Adhesives"),
    c("SRF.NS", "SRF", "Specialty Chemicals"),
    c("PIIND.NS", "PI Industries", "Agro Chemicals"),
    c("DEEPAKNTR.NS", "Deepak Nitrite", "Chemicals"),
    c("ASTRAL.NS", "Astral", "Pipes"),
    c("SUPREMEIND.NS", "Supreme Industries", "Plastics"),
    // — real estate —
    c("DLF.NS", "DLF", "Real Estate"),
    c("GODREJPROP.NS", "Godrej Properties", "Real Estate"),
    c("OBEROIRLTY.NS", "Oberoi Realty", "Real Estate"),
  ],
  Canada: [
    // — software & tech —
    c("CSU.TO", "Constellation Software", "Software"),
    c("TOI.V", "Topicus.com", "Software"),
    c("SHOP.TO", "Shopify", "Software"),
    c("OTEX.TO", "OpenText", "Software"),
    c("DSG.TO", "Descartes Systems", "Software"),
    c("KXS.TO", "Kinaxis", "Software"),
    c("ENGH.TO", "Enghouse Systems", "Software"),
    c("GIB-A.TO", "CGI Inc", "IT Services"),
    c("CLS.TO", "Celestica", "Electronics Mfg"),
    // — consumer —
    c("ATD.TO", "Alimentation Couche-Tard", "Convenience Retail"),
    c("DOL.TO", "Dollarama", "Discount Retail"),
    c("L.TO", "Loblaw Companies", "Grocery"),
    c("MRU.TO", "Metro Inc", "Grocery"),
    c("EMP-A.TO", "Empire (Sobeys)", "Grocery"),
    c("WN.TO", "George Weston", "Consumer Holdings"),
    c("SAP.TO", "Saputo", "Dairy"),
    c("PBH.TO", "Premium Brands", "Food"),
    c("QSR.TO", "Restaurant Brands (Tim Hortons)", "QSR"),
    c("MTY.TO", "MTY Food Group", "QSR Franchisor"),
    c("GIL.TO", "Gildan Activewear", "Apparel"),
    c("ATZ.TO", "Aritzia", "Apparel Retail"),
    c("GOOS.TO", "Canada Goose", "Apparel"),
    c("DOO.TO", "BRP (Ski-Doo)", "Rec Vehicles"),
    c("MG.TO", "Magna International", "Auto Parts"),
    // — rails, transport, industrials —
    c("CNR.TO", "Canadian National Railway", "Rails"),
    c("CP.TO", "Canadian Pacific Kansas City", "Rails"),
    c("TFII.TO", "TFI International", "Trucking"),
    c("WCN.TO", "Waste Connections", "Waste"),
    c("TIH.TO", "Toromont Industries", "Equipment Dealer"),
    c("FTT.TO", "Finning International", "Equipment Dealer"),
    c("RBA.TO", "RB Global (Ritchie Bros)", "Auctions"),
    c("WSP.TO", "WSP Global", "Engineering"),
    c("STN.TO", "Stantec", "Engineering"),
    c("ATRL.TO", "AtkinsRéalis", "Engineering"),
    c("BYD.TO", "Boyd Group", "Collision Repair"),
    c("CAE.TO", "CAE", "Simulation / Training"),
    c("BBD-B.TO", "Bombardier", "Business Jets"),
    c("AC.TO", "Air Canada", "Airlines"),
    c("CIGI.TO", "Colliers International", "Real Estate Services"),
    c("FSV.TO", "FirstService", "Property Services"),
    c("SJ.TO", "Stella-Jones", "Wood Products"),
    c("WFG.TO", "West Fraser Timber", "Lumber"),
    // — banks, insurance, asset mgmt —
    c("RY.TO", "Royal Bank of Canada", "Banks"),
    c("TD.TO", "TD Bank", "Banks"),
    c("BMO.TO", "Bank of Montreal", "Banks"),
    c("BNS.TO", "Bank of Nova Scotia", "Banks"),
    c("CM.TO", "CIBC", "Banks"),
    c("NA.TO", "National Bank of Canada", "Banks"),
    c("EQB.TO", "EQB Inc", "Digital Bank"),
    c("GSY.TO", "goeasy", "Consumer Lending"),
    c("EFN.TO", "Element Fleet", "Fleet Management"),
    c("IFC.TO", "Intact Financial", "P&C Insurance"),
    c("FFH.TO", "Fairfax Financial", "Insurance / Holdings"),
    c("DFY.TO", "Definity Financial", "P&C Insurance"),
    c("SLF.TO", "Sun Life Financial", "Life Insurance"),
    c("MFC.TO", "Manulife", "Life Insurance"),
    c("GWO.TO", "Great-West Lifeco", "Life Insurance"),
    c("IAG.TO", "iA Financial", "Life Insurance"),
    c("POW.TO", "Power Corporation", "Financial Holdings"),
    c("IGM.TO", "IGM Financial", "Asset Management"),
    c("X.TO", "TMX Group", "Exchange"),
    c("BN.TO", "Brookfield Corp", "Alt. Assets"),
    c("BAM.TO", "Brookfield Asset Mgmt", "Alt. Assets"),
    c("ONEX.TO", "Onex", "Private Equity"),
    c("TRI.TO", "Thomson Reuters", "Info Services"),
    // — energy & pipelines —
    c("ENB.TO", "Enbridge", "Pipelines"),
    c("TRP.TO", "TC Energy", "Pipelines"),
    c("PPL.TO", "Pembina Pipeline", "Pipelines"),
    c("KEY.TO", "Keyera", "Midstream"),
    c("ALA.TO", "AltaGas", "Midstream / Utility"),
    c("CNQ.TO", "Canadian Natural Resources", "Oil & Gas"),
    c("SU.TO", "Suncor Energy", "Oil & Gas"),
    c("IMO.TO", "Imperial Oil", "Oil & Gas"),
    c("CVE.TO", "Cenovus Energy", "Oil & Gas"),
    c("TOU.TO", "Tourmaline Oil", "Natural Gas"),
    c("PKI.TO", "Parkland", "Fuel Distribution"),
    // — utilities & telecom —
    c("FTS.TO", "Fortis", "Utilities"),
    c("EMA.TO", "Emera", "Utilities"),
    c("H.TO", "Hydro One", "Utilities"),
    c("CU.TO", "Canadian Utilities", "Utilities"),
    c("CPX.TO", "Capital Power", "Power"),
    c("NPI.TO", "Northland Power", "Renewables"),
    c("T.TO", "Telus", "Telecom"),
    c("BCE.TO", "BCE", "Telecom"),
    c("RCI-B.TO", "Rogers Communications", "Telecom"),
    c("QBR-B.TO", "Quebecor", "Telecom / Media"),
    // — materials & miners —
    c("NTR.TO", "Nutrien", "Fertilizers"),
    c("MX.TO", "Methanex", "Chemicals"),
    c("CCL-B.TO", "CCL Industries", "Packaging"),
    c("AEM.TO", "Agnico Eagle Mines", "Gold"),
    c("ABX.TO", "Barrick Gold", "Gold"),
    c("FNV.TO", "Franco-Nevada", "Royalties"),
    c("WPM.TO", "Wheaton Precious Metals", "Streaming"),
    c("K.TO", "Kinross Gold", "Gold"),
    c("CCO.TO", "Cameco", "Uranium"),
    c("TECK-B.TO", "Teck Resources", "Diversified Mining"),
    c("FM.TO", "First Quantum Minerals", "Copper"),
    c("LUN.TO", "Lundin Mining", "Copper"),
  ],
  "United States": [
    // — mega tech & semis —
    c("AAPL", "Apple", "Technology"),
    c("MSFT", "Microsoft", "Technology"),
    c("GOOGL", "Alphabet", "Communication"),
    c("AMZN", "Amazon", "Consumer / Cloud"),
    c("META", "Meta Platforms", "Communication"),
    c("NVDA", "NVIDIA", "Semiconductors"),
    c("AVGO", "Broadcom", "Semiconductors"),
    c("AMD", "AMD", "Semiconductors"),
    c("QCOM", "Qualcomm", "Semiconductors"),
    c("TXN", "Texas Instruments", "Semiconductors"),
    c("AMAT", "Applied Materials", "Semi Equipment"),
    c("LRCX", "Lam Research", "Semi Equipment"),
    c("KLAC", "KLA Corp", "Semi Equipment"),
    c("MU", "Micron", "Memory"),
    c("TSLA", "Tesla", "Autos / Energy"),
    // — software & internet —
    c("ADBE", "Adobe", "Software"),
    c("CRM", "Salesforce", "Software"),
    c("ORCL", "Oracle", "Software"),
    c("INTU", "Intuit", "Software"),
    c("NOW", "ServiceNow", "Software"),
    c("SNPS", "Synopsys", "EDA Software"),
    c("CDNS", "Cadence Design", "EDA Software"),
    c("ADSK", "Autodesk", "Software"),
    c("PANW", "Palo Alto Networks", "Cybersecurity"),
    c("CRWD", "CrowdStrike", "Cybersecurity"),
    c("FTNT", "Fortinet", "Cybersecurity"),
    c("ACN", "Accenture", "IT Services"),
    c("NFLX", "Netflix", "Streaming"),
    c("UBER", "Uber", "Platforms"),
    c("ABNB", "Airbnb", "Platforms"),
    c("BKNG", "Booking Holdings", "Travel"),
    // — payments & financials —
    c("V", "Visa", "Payments"),
    c("MA", "Mastercard", "Payments"),
    c("AXP", "American Express", "Payments / Lending"),
    c("PYPL", "PayPal", "Payments"),
    c("JPM", "JPMorgan Chase", "Banks"),
    c("GS", "Goldman Sachs", "Investment Banking"),
    c("MS", "Morgan Stanley", "Investment Banking"),
    c("WFC", "Wells Fargo", "Banks"),
    c("SCHW", "Charles Schwab", "Brokerage"),
    c("BLK", "BlackRock", "Asset Management"),
    c("BX", "Blackstone", "Alt. Assets"),
    c("KKR", "KKR", "Alt. Assets"),
    c("APO", "Apollo Global", "Alt. Assets"),
    c("BRK-B", "Berkshire Hathaway", "Conglomerate"),
    c("SPGI", "S&P Global", "Info Services"),
    c("MCO", "Moody's", "Info Services"),
    c("ICE", "Intercontinental Exchange", "Exchanges"),
    c("CME", "CME Group", "Exchanges"),
    c("NDAQ", "Nasdaq", "Exchanges"),
    c("PGR", "Progressive", "Insurance"),
    c("CB", "Chubb", "Insurance"),
    c("TRV", "Travelers", "Insurance"),
    c("MMC", "Marsh & McLennan", "Insurance Brokerage"),
    c("AON", "Aon", "Insurance Brokerage"),
    c("AJG", "Arthur J. Gallagher", "Insurance Brokerage"),
    // — healthcare —
    c("UNH", "UnitedHealth", "Managed Care"),
    c("ELV", "Elevance Health", "Managed Care"),
    c("HCA", "HCA Healthcare", "Hospitals"),
    c("MCK", "McKesson", "Drug Distribution"),
    c("LLY", "Eli Lilly", "Pharma"),
    c("ABBV", "AbbVie", "Pharma"),
    c("MRK", "Merck", "Pharma"),
    c("JNJ", "Johnson & Johnson", "Healthcare"),
    c("AMGN", "Amgen", "Biotech"),
    c("GILD", "Gilead Sciences", "Biotech"),
    c("VRTX", "Vertex Pharmaceuticals", "Biotech"),
    c("REGN", "Regeneron", "Biotech"),
    c("ZTS", "Zoetis", "Animal Health"),
    c("TMO", "Thermo Fisher", "Life Sciences"),
    c("DHR", "Danaher", "Life Sciences"),
    c("A", "Agilent", "Life Sciences"),
    c("ABT", "Abbott Laboratories", "Med Devices"),
    c("SYK", "Stryker", "Med Devices"),
    c("BSX", "Boston Scientific", "Med Devices"),
    c("ISRG", "Intuitive Surgical", "Med Devices"),
    c("EW", "Edwards Lifesciences", "Med Devices"),
    c("IDXX", "IDEXX Laboratories", "Vet Diagnostics"),
    c("BDX", "Becton Dickinson", "Med Devices"),
    // — consumer —
    c("COST", "Costco", "Retail"),
    c("WMT", "Walmart", "Retail"),
    c("TGT", "Target", "Retail"),
    c("HD", "Home Depot", "Home Improvement"),
    c("LOW", "Lowe's", "Home Improvement"),
    c("TJX", "TJX Companies", "Off-price Retail"),
    c("ROST", "Ross Stores", "Off-price Retail"),
    c("ORLY", "O'Reilly Automotive", "Auto Parts Retail"),
    c("AZO", "AutoZone", "Auto Parts Retail"),
    c("TSCO", "Tractor Supply", "Rural Retail"),
    c("LULU", "Lululemon", "Apparel"),
    c("NKE", "Nike", "Apparel"),
    c("MCD", "McDonald's", "Restaurants"),
    c("SBUX", "Starbucks", "Restaurants"),
    c("CMG", "Chipotle", "Restaurants"),
    c("YUM", "Yum! Brands", "Restaurants"),
    c("PG", "Procter & Gamble", "Staples"),
    c("KO", "Coca-Cola", "Beverages"),
    c("PEP", "PepsiCo", "Beverages"),
    c("MNST", "Monster Beverage", "Beverages"),
    c("PM", "Philip Morris Intl", "Tobacco"),
    c("MDLZ", "Mondelez", "Snacks"),
    c("HSY", "Hershey", "Confectionery"),
    c("GIS", "General Mills", "Packaged Food"),
    c("CL", "Colgate-Palmolive", "Staples"),
    c("KMB", "Kimberly-Clark", "Staples"),
    c("DIS", "Disney", "Media"),
    // — industrials —
    c("GE", "GE Aerospace", "Aerospace"),
    c("RTX", "RTX Corp", "Aerospace & Defence"),
    c("LMT", "Lockheed Martin", "Defence"),
    c("NOC", "Northrop Grumman", "Defence"),
    c("GD", "General Dynamics", "Defence"),
    c("TDG", "TransDigm", "Aerospace Parts"),
    c("HON", "Honeywell", "Industrials"),
    c("ETN", "Eaton", "Electrical"),
    c("EMR", "Emerson Electric", "Automation"),
    c("PH", "Parker Hannifin", "Motion Control"),
    c("ITW", "Illinois Tool Works", "Industrials"),
    c("CMI", "Cummins", "Engines"),
    c("PCAR", "PACCAR", "Trucks"),
    c("CAT", "Caterpillar", "Machinery"),
    c("DE", "Deere & Co", "Machinery"),
    c("UNP", "Union Pacific", "Rails"),
    c("CSX", "CSX", "Rails"),
    c("NSC", "Norfolk Southern", "Rails"),
    c("UPS", "UPS", "Logistics"),
    c("FDX", "FedEx", "Logistics"),
    c("WM", "Waste Management", "Waste"),
    c("RSG", "Republic Services", "Waste"),
    c("CTAS", "Cintas", "Uniform Services"),
    c("FAST", "Fastenal", "Distribution"),
    c("GWW", "W.W. Grainger", "Distribution"),
    c("ROP", "Roper Technologies", "Software / Industrials"),
    c("AME", "AMETEK", "Instruments"),
    c("TT", "Trane Technologies", "HVAC"),
    c("ADP", "ADP", "Payroll"),
    c("PAYX", "Paychex", "Payroll"),
    // — energy, utilities, materials —
    c("XOM", "ExxonMobil", "Oil & Gas"),
    c("CVX", "Chevron", "Oil & Gas"),
    c("COP", "ConocoPhillips", "Oil & Gas"),
    c("NEE", "NextEra Energy", "Utilities"),
    c("SO", "Southern Company", "Utilities"),
    c("DUK", "Duke Energy", "Utilities"),
    c("LIN", "Linde", "Industrial Gases"),
    c("APD", "Air Products", "Industrial Gases"),
    c("SHW", "Sherwin-Williams", "Paints"),
    c("ECL", "Ecolab", "Specialty Chemicals"),
  ],
};

export const UNIVERSE_COUNTRIES: UniverseCountry[] = ["India", "Canada", "United States"];

/** Candidates for a country, excluding symbols already held (case-insensitive). */
export function candidatesFor(country: UniverseCountry, heldSymbols: Iterable<string>): CandidateStock[] {
  const held = new Set([...heldSymbols].map((s) => s.toUpperCase().trim()));
  return UNIVERSES[country].filter((x) => !held.has(x.symbol.toUpperCase()));
}

/** Parse a user-pasted list of symbols (commas / spaces / newlines) into candidates. */
export function parseCustomSymbols(text: string, heldSymbols: Iterable<string>): CandidateStock[] {
  const held = new Set([...heldSymbols].map((s) => s.toUpperCase().trim()));
  const seen = new Set<string>();
  const out: CandidateStock[] = [];
  for (const raw of text.split(/[\s,;]+/)) {
    const s = raw.trim().toUpperCase();
    if (!s || s.length > 20 || !/^[A-Z0-9][A-Z0-9.&^=-]*$/.test(s)) continue;
    if (held.has(s) || seen.has(s)) continue;
    seen.add(s);
    out.push({ symbol: s, name: s, sector: "—" });
    if (out.length >= 100) break;
  }
  return out;
}
